### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by Anthchirp**
sync up the dependencies required by dials et al

### CODE REVIEW

**Comment by Anthchirp** [comment]
@bkpoon @phyy-nx Can I merge this? The outdated blosc dependency seems to cause issues on our RHEL6 conda builds.

**Comment by phyy-nx** [comment]
Generally for pure python packages the version isn't too important but install_base_packages uses pip to install blosc, which includes a compile step.  Since this PR bumps blosc from 1.7 from 1.8 it needs to be tested on our supported OSes.  What OSes was this tested on?

**Comment by Anthchirp** [comment]
CentOS6.10, macOS 10.14, and win_64 - apparently :)

**Comment by bkpoon** [comment]
@Anthchirp I just set up pipeline that will build base on different operating systems. Please update this branch and I can re-run that pipeline to test these changes.

**Comment by Anthchirp** [comment]
(If you're happy with it let me know and I'll squash merge for a clean history)

**Comment by Anthchirp** [comment]
This was just discussed in our DIALS meeting and we will remove blosc for DIALS 2.0, so hold on this pull request for now. Since we are the only users of blosc I will add a commit to remove it completely.

**Comment by Anthchirp** [comment]
relevant DIALS PR is dials/dials#904

**Comment by bkpoon** [comment]
Alright, the building base step passes in the new pipeline. The "Nightly Base Build" pipeline basically builds the "base" directory for dependencies and is run nightly for the master and base_updates/* branches (currently, there is a base_updates/test branch). So for future updates to base (I'll trigger a build when you next update this branch), you can just create a branch prefixed with "base_updates/" and these builds will run nightly. These builds do take a bit longer so the base_updates/* branches should be managed more actively to avoid using too many Azure Pipelines resources.

**Comment by Anthchirp** [comment]
Okay, I'll squash merge this then.

The next required dependency updates are already on the horizon. With the next release of CCP4 they will update to Pillow version "at least 5.4" (we're at 4.2.1), and I'm hoping for h5py 2.10 to be released soon.

**Comment by Anthchirp** [comment]
h5py 2.10 has now been released

**Pull request merged**
