### PR TITLE
On GPU, pre-check the exp() argument for the Gaussian shapetype

### PR DESCRIPTION
**Pull request by nksauter**
In analyzing the GPU performance of the Mullen-Holton CUDA kernel, it was discovered that significant time is spent evaluating the exp() function in double precision, signifying the offset from the Ewald sphere.  This only applies to the GAUSS shapetype for the reciprocal lattice point.  Furthermore, the argument can be checked before evaluation; if the exp() result will be essentially zero, it can be skipped.  Thread warps where all exp() values are insignificant (away from reciprocal lattice points) will coalesce, saving measurable GPU wall clock time.  The new code offers a new shapetype, GAUSS_ARGCHK where the exp() argument is pre-evaluated.

Also modified:  correctly initializing integer arrays with integer literals

### CODE REVIEW

**Comment by nksauter** [comment]
Comment from @pafonine :  Everywhere (refinement, etc) where I need to evaluate exp() a lot I use a precomputed table (available somewhere deep down in CCTBX). This saves a lot of time! I think we also do sin/cos the same way.

**Comment by biochem-fan** [comment]
Do you really need double precision? Does single precision, or the fast math version (`__expf`), lead to numerical instability? Oftentimes, only the accumulator variable needs to be `double`.

**Comment by nksauter** [comment]
Interesting question.  I don't think we have enough data to decide on float vs. double at this stage.  The motivation for double is to allow numerous contributions to a given simulated pixel that might be of widely differing magnitudes.

**Comment by biochem-fan** [comment]
It is worth investigating, because GPU is much faster with single precision numbers.

> The motivation for double is to allow numerous contributions to a given simulated pixel that might be of widely differing magnitudes.

A typical strategy in such a case is to calculate individual contributions in single precision and accumulate them into a double precision variable. For example, molecular dynamics simulation codes are often written in this way.

**Comment by bkpoon** [comment]
During the hackathon, I don't think we had the time to investigate if we could do calculations in single precision and accumulate in double precision, but I also think it would be worthwhile to check since the hardware intrinsics are going to be faster and the single precision performance is generally going to be better (~ 2x from the hardware specifications).

My only other data point is from implementing the structure factor calculation using direct summation with CUDA and there was no significant difference with the single and double precision implementations on the GPU versus the regular CPU direct summation output. My array for accumulating was not double precision for the single precision calculation, though.

**Comment by bkpoon** [comment]
The CI Branch error can be ignored.

**Comment by JBlaschke** [comment]
All of this is interesting conversion -- here are my two cents:
1) I like the fast math/argcheck/single precision approaches -- would it make sense to expose switches at compile time to select between: 1. full double; 2. fast-math; 3. argcheck; 4. single precision? I think the "best" approach might depend on whichever application that kernel is used in (eg. single precision is usually good fine if the result can be refined to double precision)
2) I am somewhat hesitant of look-up tables. I wonder how they are better than reduced precision, or argcheck?

**Review by JBlaschke — APPROVED** [review]

**Review by bkpoon — APPROVED** [review]

**Comment by pafonine** [comment]
Re tables: they've been in use in the context of crystallographic 
structure refinement since early days (read 70th or so) and that means a 
LOT of structures solved since then! Of course I have zero idea if and 
how this may fit here, so I voiced this option just for the sake of 
completeness! They do save a lot of time when exp() is called repeatedly 
many times in calculations like density sampling of structure factors 
calculation with no need to downgrade for lower precision.

Cheers,
Pavel

**Comment by biochem-fan** [comment]
@pafonine How many entries do you have in the look up table?

**Comment by russell-taylor** [comment]
That depends on the precision needed, the variability of the function, and whether you're feeding it into an iterative solver or using the built-in hardware texture interpolator to do linear interpolation.  (Note: the hardware linear interpolator has a limited interpolation precision.)  Lookup can be used as part of a multi-step process; for example, the division instruction in Intel processors uses a look-up-table based on the high-order bits in the number and then does iterations of a numerical solver to get full-resolution results.  For CUDA, you probably want to make sure that the table is entirely within constant memory for fastest lookup.  You can do the interpolation within your CUDA code, requiring two lookups for Linear and 3+ for higher-order interpolation.

**Comment by JBlaschke** [comment]
Right, thanks all for elaborating.

I know that lookup tables are a common tool when representing expensive functions -- my experience with them though was limited to CPUs (in the context of memoization).

I was curious because I found only limited examples of their use when programming accelerators. My working theory is that linear interp + lookup would consume far too much fast memory (assuming that we're aiming for double precision). There are fancier methods out there (i.e. interp + lookup + additional math), but then we're getting into the domain of specialized math functions.

Anyway, feel free to correct my assessment (which is mainly based on anecdata). I want to keep this discussion in mind though moving forward. We went with the arg check approach because it produces accurate results with reasonable performance -- while being fast to implement ;)

**Pull request merged**
