### PR TITLE
Make mtz.object.delete_reflections() efficient

### LINKED ISSUE #320: mtz.object.delete_reflections() is hideously inefficient
mtz.object.delete_reflections() is hideously inefficient when deleting a large number of reflections. This can end up being a bottle neck in the xia2 rebatch function:

https://github.com/xia2/xia2/blob/70a87331b22cd0b2d378b6a0ed120f483ca52ece/Modules/Scaler/rebatch.py#L88

https://github.com/cctbx/cctbx_project/blob/666f100f60722b554cc7f8e440eb14bfe9a27f8f/iotbx/mtz/object.h#L575-L585

See comment above in the code for delete_reflections (which is called by delete_reflections for every reflection being deleted):
https://github.com/cctbx/cctbx_project/blob/666f100f60722b554cc7f8e440eb14bfe9a27f8f/iotbx/mtz/object.h#L568-L573

### PR DESCRIPTION
**Pull request by Anthchirp**
On deleting multiple entries create a new array and copy all remaining
elements into the new array in O(n).

This replaces the previous implementation where each element is removed
individually by shifting the remainder of the array one place forward
in O(n²).

Fixes #320

### CODE REVIEW

**Comment by graeme-winter** [comment]
Quick look, seems sensible - deleting reflections I have found problematic in the past so thanks for looking at this.

**Comment by rjgildea** [comment]
Tested this with the following script:
```
from __future__ import absolute_import, division, print_function

import time
import sys

import iotbx.mtz
from scitbx.array_family import flex

def run(args):
    assert len(args) == 1
    filename = args[0]
    obj = iotbx.mtz.object(filename)

    for n_delete in (1, 2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000):
        nref_orig = obj.n_reflections()
        if n_delete > nref_orig:
            break
        iref = flex.sorted(flex.random_permutation(obj.n_reflections())[:n_delete])
        t0 = time.time()
        obj.delete_reflections(iref)
        t = time.time() -t0
        assert obj.n_reflections() == nref_orig - n_delete
        print("%4i: %fs" % (n_delete, t))


if __name__ == "__main__":
    run(sys.argv[1:])
```
on an example unmerged reflection file with >6 million observations `/dls/mx-scratch/rjgildea/performance_week/firehose/001/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.mtz`.

Timings with original implementation:
```
   1: 0.038522s
   2: 0.074254s
   5: 0.080070s
  10: 0.268641s
  20: 0.449388s
  50: 0.898962s
 100: 2.601796s
 200: 4.928543s
 500: 12.040385s
1000: 24.746426s
2000: 49.419131s
5000: 119.079113s
```

Timings with new implementation:
```
   1: 0.161734s
   2: 0.171613s
   5: 0.153348s
  10: 0.150927s
  20: 0.149846s
  50: 0.153441s
 100: 0.151782s
 200: 0.155939s
 500: 0.149971s
1000: 0.156159s
2000: 0.149077s
5000: 0.156631s
```
The new implementation completes in a constant time regardless of the number of deleted reflections. It is marginally slower when deleting fewer than ~10 reflections, but significantly faster with many more reflections.

**Comment by Anthchirp** [comment]
slower for small `n` is to be expected as elements are copied individually rather than collectivelvia `memmove()` in a conditional loop, so unlikely to be optimized by the compiler. I'd say that a 0.1s cost is likely to be fine in all cases though and not worth the effort to optimize this further.

**Comment by Anthchirp** [comment]
I understood this as a programming exercise, and have changed the algorithm from an element-wise to a block-wise copy. The new implementation is now faster in all cases where N>1.

N | original | new
--- | --- | ---
   1 | 0.066203s | 0.271656s
   2 | 0.132401s | 0.071052s
   5 | 0.334103s | 0.044182s
  10 | 0.667886s | 0.045340s
  20 | 1.351719s | 0.045298s
  50 | 3.347832s | 0.045534s
 100 | 6.569747s | 0.044925s
 200 | 13.138928s  | 0.045242s
 500 | 32.789561s | 0.045194s
1000 | 66.570445s | 0.044691s
2000 | 131.479574s | 0.044265s
5000 | 329.646579s | 0.044940s

I have also validated the output by looking at the column values using:
```python
from __future__ import absolute_import, division, print_function                                                        
                                                                                                                        
import time                                                                                                             
import sys                                                                                                              
                                                                                                                        
import iotbx.mtz                                                                                                        
from scitbx.array_family import flex                                                                                    
                                                                                                                        
filename = "/dls/mx-scratch/rjgildea/performance_week/firehose/001/DataFiles/AUTOMATIC_DEFAULT_scaled_unmerged.mtz"     
if __name__ == "__main__":                                                                                              
    obj = iotbx.mtz.object(filename)                                                                                    
                                                                                                                        
    for n_delete in (1, 2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000):                                             
        nref_orig = obj.n_reflections()                                                                                 
        if n_delete > nref_orig:                                                                                        
            break                                                                                                       
        permutation = flex.sorted(flex.random_permutation(obj.n_reflections()))                                         
        keep = permutation[n_delete:]                                                                                   
        iref = permutation[:n_delete]                                                                                   
        old_column = list(obj.columns())[0].extract_values()                                                            
        t0 = time.time()                                                                                                
        obj.delete_reflections(iref)                                                                                    
        t = time.time() -t0                                                                                             
        assert obj.n_reflections() == nref_orig - n_delete                                                              
        new_column = list(obj.columns())[0].extract_values()                                                            
        assert len(new_column) == len(old_column) - n_delete
        old_column = old_column.select(keep)                                                                            
        assert (old_column == new_column).all_eq(True)                                                                  
        print("%4i: %fs" % (n_delete, t))                           
```

**Comment by Anthchirp** [comment]
Question was asked why deleting 1 is slower than deleting 10. I've updated the code to delete (1, 1, 2, 1, 2, 5, 10, ...), which shows that this is initialisation overhead. As to why this happens in the new implementation but not in the old one I have no idea.

**Pull request merged**
