### PR TITLE
"Truncate" XFEL expts/refls based on aggregated statistics

### PR DESCRIPTION
**Pull request by Baharis**
This PR ports the changes discussed in PR #1001 outside postrefinement into a dedicated `truncate` worker. In contrast to `postrefine` or `filter` workers, the `truncate` worker is strictly designed to act on the entire dataset and utilize global communication instead of refraining from using it. For the time being, it utilizes only the "intensity extrema threshold" mechanism described in PR #1001; however, it is strictly designed to be expanded by additional "truncation" criteria.

For more details on the mechanism behind the rejection mechanism, refer to #1001.

Bugfixes and code clean-up introduced to the `postrefine` worker are not moved here and have been made into a separate PR #1002 instead.

### CODE REVIEW

**Review by phyy-nx — APPROVED** [review]

**Comment by Baharis** [comment]
Example output (from new XFEL regression test):
```
STEP 1: Read experiments and data
Experiments: (total,min,max): 33, 33, 33
Images:      (total,min,max): 33, 33, 33
Reflections: (total,min,max): 3561, 3561, 3561

STEP 2: Filter expts & refls based on their aggregated statistics
Experiments/reflections truncated globally due to:
- Intensity extremum outside IQR dist threshold:      7 expt,      1142 refl
- TOTAL:                                              7 expt,      1142 refl
Experiments: (total,min,max): 26, 26, 26
Images:      (total,min,max): 26, 26, 26
Reflections: (total,min,max): 2419, 2419, 2419
```

**Comment by nksauter** [comment]
I'm concerned that the name "Truncate" conflicts with another well-known algorithm in protein crystallography implemented about 50 years ago and used ever since; namely the French-Wilson treatment that makes all merged intensities positive in the merging output.  I'd favor choosing another name to avoid the conflict.

**Comment by Baharis** [comment]
I renamed and moved the `truncate` worker into `filter_global`. The only problem with this name is that `global` is a reserved name in python and, as such, the corresponding phil scope for this worker must not have a `.global.` segment in it. I solved it using the standard Python practice of adding an underscore, i.e. the threshold parameter is not `filter.global_.intensity_extrema_iqr_dist_threshold`, but it can be unintuitive; another approach would be to give this worker its own phil scope, e.g. `filter_global.intensity_extrema_iqr_dist_threshold`, similarly to how experiment worker and reflection worker use `filter` and `select`, accordingly, but this might be even more confusing.

**Comment by Baharis** [comment]
Following Nick's remark on yesterday's SPREAD meeting, I plotted the distribution of max(intensity sum) versus min(intensity sum) for all 111k indexed PSII experiments to see how it looks. Since most minima are negative, I used an absolute value on the Y axis, with red points representing minima > 0 and blue points representing minima < 0. As you can see, the distribution of extrema is roughly log-normal (suggesting that, if we care enough, the threshold limit would also be better set in the log space). Surprisingly, despite ~60 expts being removed in this step, I could find only 3 that clearly surpass the threshold for maxima.
image

**Pull request merged**
