### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by Anthchirp**
* Update various packages
* Remove junit-xml (superseded by pytest)
* Download py2app from pypi

When merging, suggest to merge pull request #205 first as there are overlaps.

### CODE REVIEW

**Comment by nksauter** [comment]
Would rather agree on a policy where package dependencies for CCTBX are
updated on a fixed schedule, for example, once per year on January 15.

Could we try it out on Jan. 15 and see how it works?

Nick

Nicholas K. Sauter, Ph. D.
Senior Scientist, Molecular Biophysics & Integrated Bioimaging Division
Lawrence Berkeley National Laboratory
1 Cyclotron Rd., Bldg. 33R0345
Berkeley, CA 94720
(510) 486-5713

**Comment by graeme-winter** [comment]
Is this still blocked by something? 

I have shop floor support requirements which need some of these updates to come through now i.e. supporting new instruments that we have paid a lot of money for.

**Comment by Anthchirp** [comment]
Due to #205 being merged by rebasing this now shows a merge conflict. Fix by rebasing this branch.

**Comment by phyy-nx** [comment]
Hi, does this compile on Centos 6, 7, Ubuntu 14.04, 16.04, and mac os 10.11-13?  See https://github.com/cctbx/cctbx_project/issues/85#issuecomment-398926708, except that we are deprecating Centos 5 and 32 bit versions.

As part of the conda work, we'll be adding more testing environments that run nightly.  We have Centos 6, 7 and mac os 10.11 running nightly now.  We just run the tests manually on the above list when we update the dependencies.  If ${someone} does the same on the above list, this PR can be merged.

**Comment by Anthchirp** [comment]
If you have the tests running then the easiest way to check is to merge, wait for a day, and then treat any issues as bugs?

**Comment by phyy-nx** [comment]
Hi, we have the tests running on Centos 6, 7 and mac os 10.11.  They are not running on Ubuntu 14.04, 16.04, and mac os 10.12-13.  Typically when dependencies change we load up vms and and test these platforms manually, but it takes time.  Hence the call for $someone to do the tests on Ubuntu 14.04, 16.04, and mac os 10.12-13 before we merge this PR.

**Comment by Anthchirp** [comment]
Built on Ubuntu 14.04 and 16.04 using
```
sudo apt-get install git g++ zlib1g-dev xorg-dev libbz2-dev
git clone https://github.com/cctbx/cctbx_project.git modules/cctbx_project -b package-updates
cp modules/cctbx_project/libtbx/auto_build/bootstrap.py .
python bootstrap.py -v --builder=dials --nproc=4 hot update base build
```
(Thanks to @benjaminhwilliams and @ndevenish for figuring out required package prerequisites)
then tested with
```
python bootstrap.py -v --builder=dials --nproc=4 tests
```
Same on Mac but without the ```apt-get``` bit.
All successful, therefore merging.

**Comment by Anthchirp** [comment]
@ndevenish found an issue with updating freetype on RHEL7 which we have not caught earlier. Apparently freetype no longer wants to work with our version of harfbuzz, causing the compilation of pango to fail. Interestingly enough this does work fine on RHEL6. Will investigate and open a new pull request once I have run some more tests. For now I have reverted the freetype update.

**Pull request merged**
