### PR TITLE
Lunus merging worker

### PR DESCRIPTION
**Pull request by phyy-nx**
Add a worker to cctbx.xfel.merge to run [Lunus](https://github.com/lanl/lunus.git) on integrated images using MPI.  Will be used for analysis of diffuse scattering from protein crystals. Includes test added to xfel_regression and the XFEL Azure CI.

Co-authored-by: Mike Wall <mewall@lanl.gov>

### CODE REVIEW

**Comment by mewall** [comment]
I'm seeing a couple of tests failing. E.g.:


https://github.com/cctbx/cctbx_project/pull/622/checks?check_run_id=2835150258



https://github.com/cctbx/cctbx_project/pull/622/checks?check_run_id=2834988364


One of these looks like it's a psana test.


Thoughts?



________________________________
From: azure-pipelines[bot] ***@***.***>
Sent: Thursday, June 17, 2021 5:28:57 AM
To: cctbx/cctbx_project
Cc: Wall, Michael E; Review requested
Subject: [EXTERNAL] Re: [cctbx/cctbx_project] Lunus merging worker (#622)


Azure Pipelines successfully started running 3 pipeline(s).

**Comment by phyy-nx** [comment]
I re-ran the pipeline on master and all the tests pass. I don't know why the test on this PR failed.  I've restarted the tests here to see if it was intermittent.

**Comment by phyy-nx** [comment]
I think it's ok.  The failures on on the branch pipelines.  The [PR pipeline passed](https://dev.azure.com/cctbx/cctbx_project/_build/results?buildId=14753&view=results).  So I'll merge this EOB today.

**Comment by mewall** [comment]
Great, thanks! -- Mike

________________________________
From: Aaron S. Brewster ***@***.***>
Sent: Thursday, June 17, 2021 8:49:30 AM
To: cctbx/cctbx_project
Cc: Wall, Michael E; Review requested
Subject: [EXTERNAL] Re: [cctbx/cctbx_project] Lunus merging worker (#622)


I think it's ok. The failures on on the branch pipelines. The PR pipeline passed<https://dev.azure.com/cctbx/cctbx_project/_build/results?buildId=14753&view=results>. So I'll merge this EOB today.

**Review by mewall — APPROVED** [review]

**Pull request merged**
