### PR TITLE
diffBragg 

### PR DESCRIPTION
**Pull request by dermen**
code needed to reproduce the upcoming exascale story report

### CODE REVIEW

**Comment by nksauter** [comment]
Please try to find a way to suppress or workaround the nvcc compiler warnings arising from the Eigen headers.

Also, three tests produce errors: 
DIFFBRAGG_USE_CUDA=1 libtbx.python "/global/cscratch1/sd/nksauter/adse13_187/bleededge/alcc-recipes/cctbx/modules/cctbx_project/simtbx/diffBragg/tests/tst_diffBragg_ncells_offdiag_property.py" --idx 1 [FAIL] 28.0s
  Return code: 188
DIFFBRAGG_USE_CUDA=1 libtbx.python "/global/cscratch1/sd/nksauter/adse13_187/bleededge/alcc-recipes/cctbx/modules/cctbx_project/simtbx/diffBragg/tests/tst_diffBragg_ncells_offdiag_property.py" [FAIL] 28.0s
  Return code: 188
DIFFBRAGG_USE_CUDA=1 libtbx.python "/global/cscratch1/sd/nksauter/adse13_187/bleededge/alcc-recipes/cctbx/modules/cctbx_project/simtbx/diffBragg/tests/tst_diffBragg_ncells_offdiag_property.py" --idx 2 [FAIL] 28.0s
  Return code: 188

**Comment by nksauter** [comment]
Revisit the run_tests.py.  Tests should be run with and without the DIFFBRAGG_USE_CUDA=1 environment variable.   Obvious options would be to extend the run_tests_parallel.py command so as to handle command prefixes, or to implement the cuda option as a command line argument instead.

**Comment by nksauter** [comment]
Please add @bkpoon as a reviewer due to the modifications to libtbx/SConscript

**Comment by nksauter** [comment]
Has conflicts with master branch; need to resolve.

**Comment by bkpoon** [comment]
The conflict is with the spacing in the `arch_flags.pop()` line that was just added in 8103a20c4353b1055a36ba5f983f1cfb92358e2d. Can you rebase your branch on `master`? It looks like you picked up some clutter that is not in `master`.

**Review by bkpoon — APPROVED** [review]

**Pull request merged**
