### PR TITLE
Add r_anom to merging_statistics output

### PR DESCRIPTION
**Pull request by rjgildea**
Example output:
```
$ iotbx.merging_statistics $(dials.data get -q x4wide_processed)/AUTOMATIC_DEFAULT_scaled_unmerged.mtz
Format: ccp4_mtz
Miller array info: /Users/rjgildea/software/cctbx_py3/build/dials_data/x4wide_processed/AUTOMATIC_DEFAULT_scaled_unmerged.mtz:I,SIGI
Observation type: xray.intensity
Type of data: double, size=66052
Type of sigmas: double, size=66052
Number of Miller indices: 66052
Anomalous flag: False
Unit cell: (42.3695, 42.3695, 39.6915, 90, 90, 90)
Space group: P 41 21 2 (No. 92)

                     ----------Merging statistics----------                    

Resolution: 29.96 - 1.20
Observations: 66005
Unique reflections: 11773
Redundancy: 5.6
Completeness: 99.75%
Mean intensity: 400.1
Mean I/sigma(I): 6.1
R-merge: 0.100
R-meas:  0.110
R-pim:   0.045

Redundancies (non-anomalous):
  1 : 172
  2 : 619
  3 : 1048
  4 : 1556
  5 : 1955
  6 : 2489
  7 : 1997
  8 : 1200
  9 : 486
  10 : 202
  11 : 43
  12 : 6

  Statistics by resolution bin:
 d_max  d_min   #obs  #uniq   mult.  %comp       <I>  <I/sI>    r_mrg   r_meas    r_pim   r_anom   cc1/2   cc_ano
 29.97   2.58   7074   1288    5.49  99.31    2336.0    17.7    0.052    0.057    0.023    0.080   0.998   0.512
  2.58   2.05   7032   1203    5.85  99.83     725.8    12.7    0.114    0.125    0.050    0.113   0.983  -0.032
  2.05   1.79   6594   1187    5.56  99.83     293.2     8.4    0.167    0.183    0.074    0.161   0.969  -0.087
  1.79   1.63   6876   1171    5.87 100.00     166.1     6.7    0.200    0.220    0.088    0.185   0.959  -0.147
  1.63   1.51   6546   1165    5.62  99.74      92.4     4.4    0.252    0.277    0.114    0.244   0.947  -0.004
  1.51   1.42   6390   1158    5.52  99.74      60.3     3.2    0.314    0.346    0.143    0.295   0.905  -0.166
  1.42   1.35   6823   1166    5.85 100.00      38.2     2.3    0.407    0.447    0.180    0.381   0.898  -0.061
  1.35   1.29   5965   1141    5.23  99.30      23.2     1.4    0.538    0.595    0.250    0.525   0.850  -0.048
  1.29   1.24   6414   1150    5.58 100.00      18.9     1.2    0.649    0.715    0.296    0.557   0.845  -0.047
  1.24   1.20   6291   1144    5.50  99.74      14.0     0.8    0.860    0.950    0.396    0.705   0.752  -0.031
 29.96   1.20  66005  11773    5.61  99.75     400.1     6.1    0.100    0.110    0.045    0.119   0.998   0.356

References:
  Diederichs K & Karplus PA (1997) Nature Structural Biology 4:269-275
    (with erratum in: Nat Struct Biol 1997 Jul;4(7):592)
  Weiss MS (2001) J Appl Cryst 34:130-135.
  Dauter, Z. (2006). Acta Cryst. D62, 867-876.
  Karplus PA & Diederichs K (2012) Science 336:1030-3.
```

### CODE REVIEW

**Review by dagewa — APPROVED** [review]
I'm just digging in to confirm that the values output are correct, but as far as the display of those values goes, this is great, thanks.

**Comment by dagewa** [comment]
Correct me if I'm wrong, but it looks to me that the cctbx implementation of R_anom includes the calculation of |F(+) - F(-)| rather than |I(+) - I(-)| and therefore does not match the [referenced paper](https://journals.iucr.org/d/issues/2006/08/00/dz5079/index.html).

**Comment by dagewa** [comment]
At least, it calls this function 
https://github.com/cctbx/cctbx_project/blob/6590ee31e3373b1934363a5ed569a2fd57b2e6f8/cctbx/miller/__init__.py#L2954-L2958
which mentions F(+) - F(-) in the docstring, but maybe this is actually I(+) - I(-) if the input is an intensity array?

**Comment by rjgildea** [comment]
> At least, it calls this function
> https://github.com/cctbx/cctbx_project/blob/6590ee31e3373b1934363a5ed569a2fd57b2e6f8/cctbx/miller/__init__.py#L2954-L2958
> 
> 
> which mentions F(+) - F(-) in the docstring, but maybe this is actually I(+) - I(-) if the input is an intensity array?

This function will return dI if passed intensities as input, and dF if passed amplitudes, i.e. there is not conversion to/from intensities.

The first line of the `r_anom` asserts that it was passed an intensity array as input, so it _should_ do the right thing:
https://github.com/cctbx/cctbx_project/blob/6590ee31e3373b1934363a5ed569a2fd57b2e6f8/cctbx/miller/__init__.py#L5207

**Comment by dagewa** [comment]
I see - I was misled by the docstring

**Comment by rjgildea** [comment]
It isn't obvious to me that the test failures have anything to do with the changes in this PR.

**Comment by phyy-nx** [comment]
Right, it seems the XFEL CI test is intermittently failing right now.  Might be a conda environment instability as none of the code that would affect these tests has been modified (here or in master), to my knowledge.

I just checked into xfel_regression some additional diagnostics to try and sort this out.  The two test failures here shouldn't be a blocker to merging this PR.

**Comment by bkpoon** [comment]
The XFEL CI is intermittent and @phyy-nx is looking into it. That's why XFEL CI passed, but XFEL CI branch failed after you updated your branch.

Generally, the CI branch and XFEL CI branch pipelines are less important because it only runs on the current state of that particular branch. The Checks, Full, Base, and XFEL CI pipelines run on the [merged code](https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#pr-triggers) so I generally only look at those results.

Thanks! I'll add a new column to the Phenix GUI to show this result.

**Review by bkpoon — APPROVED** [review]

**Comment by phyy-nx** [comment]
I know this is a semi random place to put this information, but since XFEL CI came up here I thought I'd put it here.  I have probably fixed XFEL CI?  This issue is there are two versions of MPI available, OpenMPI and mpich.  [We don't specify](https://github.com/cctbx/cctbx_project/blob/master/xfel/conda_envs/psana_environment.yml#L13) the version to use when installing psana, so it appears conda [picks one](https://dev.azure.com/cctbx/3d754415-9516-43fb-8e21-e1fae873ee5e/_apis/build/builds/9958/logs/65), and it seems to pick different versions sometimes.  One of the versions doesn't accept a parameter I am using in my test, so my test should now check the version and use the parameter only if it is available.

**Pull request merged**
