### PR TITLE
Fix get_gcc_version so that it doesn't return 'None' when gcc emits warnings into stderr

### PR DESCRIPTION
**Pull request by JBlaschke**
The current `get_gcc_version` function (in `libtbx/env_config.py`) deliberately returns `None` when `stderr` is non-empty. However, sometimes a compiler will output warnings in `stderr` (and still a valid version number in`stdout`). In these cases, the returned `None` can interfere with the build process.

This version still outputs `None`, if it fails to find a valid version number in `buffer.stdout`... so if your compiler is actually screwy, this is where the build system breaks (I guess that's what the `len(buffer.stderr)` business was all about).

### CODE REVIEW

**Comment by JBlaschke** [comment]
@bkpoon bumping this (if you have time)

**Comment by bkpoon** [comment]
Does this fix the problem on Cori or on Summit? Which system should I test?

**Comment by JBlaschke** [comment]
> Does this fix the problem on Cori or on Summit? Which system should I test?

@bkpoon building on Cori exposed this problem. But it fixes a general issue: if `gcc` puts anything in `stderr` (like `libreadline` warnings), then the build fails because we're not processing the version number.

**Comment by bkpoon** [comment]
Thanks!

**Pull request merged**
