### PR TITLE
implementation of the shelx RIGU restraint for smtbx

### PR DESCRIPTION
**Pull request by pascal22p**
Hi,

here is the implementation of the shelx RIGU restraint for smtbx.
All tests passes. This is only new stuff, I have not modified existing features. At least not intentionally.

### CODE REVIEW

**Comment by Anthchirp** [comment]
I just received a notification from github saying you pushed 89 commits. Without looking at the actual changes - may I request that before this pull request is merged that all merge commits are removed from the pull request and the number of commits is drastically reduced? Alternatively it should only be merged as a squash merge (ie. combine everything into a single commit)

The [graphical pull request history](https://github.com/cctbx/cctbx_project/network) does not appear to be very linear, so maybe it can also be broken up into multiple smaller pull requests?

I also just saw that the pull requests contains [commits dating from 2016](https://github.com/cctbx/cctbx_project/pull/231/commits/edd4034572d8acf9af0fa0e977cb7f384c51c474). Is this intentional or did maybe something go wrong in your branch?

**Comment by graeme-winter** [comment]
@pascal22p I am not much of an expert on Git, but when I get into situations like this I tend to ask @Anthchirp to help "fix my Git" - if you feel the same please feel free to call in some help 🙂

**Comment by pascal22p** [comment]
Hummm. Oops? I will fix it. Probably a rebase/merge mess somewhere...

**Comment by pascal22p** [comment]
If there is no more objections, could anyone merge this?

**Comment by Anthchirp** [comment]
History looks a lot better now and would suggest to **squash** merge once @olegsobolev 's points 1 & 2 are addressed.

Bit surprised at point 3 I have to say. This is a very high bar for external collaborators. If there are any issues caused by this change we should find out relatively quickly thanks to test coverage and if any issues show up on some rare platforms later on then we can adress them at that time or -worst case- revert the change at any time - so I don't think this should be a requirement?
It's not my code/module though, so it is not my call.

**Comment by pascal22p** [comment]
Where can I find phenix_regression/pdb/enk_11i.res?

**Comment by graeme-winter** [comment]
```
TITL qq
CELL  0.7   10.851   13.095   21.192 100.00  80.00  75.00
ZERR        4    0.011    0.013    0.021   0.00   0.00   0.00
REM Space group P1
LATT -1
SYMM X, Y, Z

SFAC  C  O N

C1    1    0.793115    0.207440    0.258374     0.97274    0.01121    0.00925 =
         0.01486    0.00044   -0.00083   -0.00057
C2    1    0.790830    0.216310    0.330617     0.96574    0.01538    0.01117 =
         0.01136    0.00023   -0.00144    0.00141
C3    1    0.829443    0.119313    0.364128     0.95084    0.01011    0.01174 =
         0.01183    0.00010   -0.00061    0.00062
C4    1    0.768305    0.087339    0.418495     0.96877    0.01468    0.01868 =
         0.01787    0.00578    0.00495    0.00458
C5    1    0.806665    0.000964    0.451760     0.97751    0.01596    0.01915 =
         0.01917    0.00783    0.00380    0.00314
C6    1    0.908485   -0.054153    0.430603     0.98523    0.01497    0.01251 =
         0.01552    0.00248   -0.00270   -0.00013
C7    1    0.970484   -0.022926    0.376529     0.99015    0.01856    0.01707 =
         0.01655    0.00336    0.00424    0.00497
C8    1    0.930930    0.063050    0.344023     0.98048    0.01716    0.01732 =
         0.01581    0.00396    0.00547    0.00436
C9    1    0.704788    0.125181    0.235174     0.94516    0.00932    0.00810 =
         0.01205    0.00041    0.00030    0.00005
C10   1    0.670847   -0.032617    0.179928     0.98363    0.01381    0.01208 =
         0.01662   -0.00416    0.00145   -0.00162
C11   1    0.591772   -0.081892    0.230854     0.95313    0.01071    0.00788 =
         0.01706   -0.00141    0.00087    0.00051
C12   1    0.576074   -0.138641    0.338702     0.99514    0.01645    0.01415 =
         0.02314    0.00612   -0.00018    0.00285
C13   1    0.463759   -0.077181    0.358127     0.96537    0.01353    0.01095 =
         0.01286    0.00333   -0.00136   -0.00215
C14   1    0.358597    0.088484    0.360090     0.98615    0.01136    0.01177 =
         0.01181    0.00017   -0.00092    0.00016
C15   1    0.401008    0.189312    0.389454     0.97919    0.01716    0.01202 =
         0.01369   -0.00132   -0.00157   -0.00054
C16   1    0.460723    0.182167    0.453727     0.99044    0.01223    0.01476 =
         0.01260   -0.00199   -0.00049    0.00012
C17   1    0.504681    0.272563    0.480264     0.97226    0.02096    0.01545 =
         0.01846   -0.00394   -0.00589    0.00035
C18   1    0.558297    0.273668    0.539895     0.98605    0.02646    0.02151 =
         0.02144   -0.00648   -0.00467   -0.00227
C19   1    0.569642    0.183109    0.574024     0.97771    0.01824    0.02624 =
         0.01372   -0.00234   -0.00329   -0.00563
C20   1    0.527139    0.092038    0.547813     0.98592    0.02067    0.02293 =
         0.01339    0.00166   -0.00291   -0.00725
C21   1    0.473097    0.091651    0.488060     0.98859    0.01934    0.01709 =
         0.01175    0.00095   -0.00159   -0.00458
C22   1    0.275554    0.111720    0.303173     0.93185    0.00853    0.01313 =
         0.01006    0.00022    0.00035    0.00131
C23   1    0.225333    0.082724    0.192444     0.97520    0.01048    0.01238 =
         0.00883   -0.00021   -0.00012    0.00093
C24   1    0.296312    0.039165    0.135716     0.95935    0.01291    0.01627 =
         0.01057   -0.00008    0.00185    0.00369
C25   1    0.248311    0.070450    0.070915     0.93956    0.01052    0.01665 =
         0.01028   -0.00188   -0.00004    0.00011
C26   1    0.271738    0.183044    0.057581     0.98459    0.03620    0.01816 =
         0.02026    0.00373    0.00122    0.00520
C27   1    0.311187    0.003987    0.020945     0.95596    0.01994    0.02227 =
         0.01471   -0.00688    0.00298   -0.00162
C28   1    0.098509    0.030802    0.198512     0.97479    0.00966    0.01222 =
         0.01193   -0.00220   -0.00038    0.00202
O1    2    0.950513   -0.139430    0.460881     1.00000    0.02223    0.01714 =
         0.01875    0.00607   -0.00016    0.00258
O2    2    0.592672    0.134195    0.245850     0.98674    0.01078    0.01290 =
         0.01959   -0.00013    0.00172   -0.00016
O3    2    0.483393   -0.106222    0.220450     0.99948    0.01209    0.01515 =
         0.02306   -0.00248   -0.00040   -0.00278
O4    2    0.378641   -0.120693    0.387000     0.97299    0.01824    0.01429 =
         0.02162    0.00493    0.00445   -0.00322
O5    2    0.188187    0.171166    0.309767     0.98913    0.01881    0.02518 =
         0.01621   -0.00313   -0.00011    0.01071
O6    2    0.094723   -0.055979    0.224338     0.99596    0.01400    0.01273 =
         0.02470    0.00309    0.00095   -0.00031
O7    2    0.006681    0.076629    0.176127     0.98816    0.01016    0.01806 =
         0.01890    0.00207   -0.00173    0.00318
N1    3    0.748866    0.306635    0.231035     0.98200    0.01505    0.01048 =
         0.01579    0.00167   -0.00121   -0.00120
N2    3    0.752990    0.045799    0.204510     0.97363    0.00939    0.00964 =
         0.01637   -0.00219    0.00267   -0.00094
N3    3    0.645402   -0.094185    0.287600     0.97219    0.01060    0.01399 =
         0.01769    0.00319    0.00069    0.00026
N4    3    0.461680    0.022737    0.344423     0.99679    0.01157    0.01120 =
         0.01374    0.00305    0.00038   -0.00066
N5    3    0.300208    0.064679    0.248591     0.97607    0.01006    0.01579 =
         0.00954   -0.00175   -0.00184    0.00260
```

for convenience

**Comment by olegsobolev** [comment]
1. Tests are failing: iotbx/cif/tests/tst_restraints.py, cctbx/adp_restraints/tst_ext.py
2. Eps in approx_equal is 1e-6 by default. Therefore -2.22044604925e-16 is essentially 0. Let alone 6.57384087684e-34. I suggest to change it to 0 for clarity and to not mislead others about precision. 
3. It would be nice to have test case where delta_13 and delta_23, residuals and gradient != 0.

@Anthchirp , after discussion with @bkpoon we agreed to merge when ready and rely on our nightly builds infrastructure for testing in this particular case. Therefore merge will be done in beginning-mid week. For common policy we'll need to have wider discussion elsewhere.

**Comment by pascal22p** [comment]
3. Atoms are nearly isotropic causing 13 and 23 to tend to zero. I would need a better suited res file.

I am stuck with the finite difference. RIGU is composed of 3 individuals restraints and actually the residual is the sum of the 3 which does not give me a valid derivative from finite difference. I need to investigate.

**Comment by pcxod** [comment]
Superseded by #295

**Pull request closed without merging**
