### PR TITLE
Reduce2 speedup

### PR DESCRIPTION
**Pull request by russell-taylor**

### CODE REVIEW

**Comment by russell-taylor** [comment]
@bkpoon It looks like when I ran libtbx.clean_clutter, it caused conflicts that must be resolved before the merge. None of these are in files that I modified. What is the best way to proceed?

**Comment by russell-taylor** [comment]
@bkpoon It looks like they will be straightforward to resolve using the Github tools. If the pull requests passes the checks, I'll go ahead and give that a try.

**Comment by russell-taylor** [comment]
@bkpoon Actually, there is a non-trivial difference in mmtbx/ligands/hierarchy_utils.py where I don't know whether the removal of the code is the right thing to do or not. Can you have a look at that and let me know?

**Comment by bkpoon** [comment]
There were some recent changes to mmCIF/PDB handling. Did you make many commits? It may be easier to create a new branch starting with `master` and then cherry-picking your new commits.

**Comment by russell-taylor** [comment]
I made enough that I'm not confident that I can pick them out of the 377 total commits.  If you can easily determine the right thing to do with the one I pointed out, I'm okay doing the merge. Otherwise, I'll probably try checking the new files and old files out separately and just jamming the new ones in with a commit that has all of the comments I can find.

I tried a rebase, but it failed before I did the merge with master.

**Comment by bkpoon** [comment]
Let me see if I can cherry-pick into a new branch. In the list shown above, it should the commits that only have you as the committer.

**Comment by nksauter** [comment]
Just a heads up. I plan to merge PR#957 at 12:00 Pacific today.

**Comment by bkpoon** [comment]
That should be fine. I want to get a branch with just Russell's changes that can be rebased on top of `master`.

**Comment by bkpoon** [comment]
This should show @russell-taylor commits since Nov 1, 2023 in the `reduce2-speedup` branch.
https://github.com/cctbx/cctbx_project/commits/reduce2-speedup?author=russell-taylor&since=2023-11-01&until=2024-02-06

**Comment by russell-taylor** [comment]
I get conflicts when I try to cherry-pick those, in xfel/euxfel/definitions for one of them.  It looks like it was a commit that you and I  jointly made?

**Comment by russell-taylor** [comment]
Sorry, I'll check the rs2 branch.

**Comment by russell-taylor** [comment]
Closing in favor of Billy's better branch.

**Pull request closed without merging**
