### PR TITLE
Smtbx commandline refinement

### PR DESCRIPTION
**Pull request by dwpaley**
This makes some changes to improve the correctness and usability of the small smtbx script smtbx/command_line/refine.py. 

Previously inelastic scattering factors were not loaded, partly because the refinement.model didn't know the X-ray wavelength. This pull request gives the model access to the wavelength by modifying the iotbx model builders for input cif and shelx files. The objects cctbx.xray.structure and smtbx.refinement.model are given a wavelength attribute which is initialized to None by default.

File input/output is also improved by (1) fixing the file path checking when an hklf format specifier is included, and (2) writing output cif in corecif format instead of mmcif.

Edit: Pull request was amended after running libtbx.clean_clutter

### CODE REVIEW

**Comment by pafonine** [comment]
Please add a test and make sure methods like copy, deep_copy, select deal with this parameter correctly

**Comment by dwpaley** [comment]
Ok, thanks. Do you have any example at hand that I could model the test
after?

**Comment by pafonine** [comment]
Look in cctbx/regression.

**Comment by graeme-winter** [comment]
@dwpaley to give a more detailed answer - 

in `cctbx_project/cctbx/regression/tst_xray.py` there is a function `exercise_structure` which exercises the constructors and so on. 

In `cctbx_project/iotbx/cif/tests` there is code for testing CIF things, and in `cctbx_project/iotbx/shelx/tst_*.py` code for exercising the shelx interfaces. 

I don't see any integration tests for `smtbx.refine` - perhaps these are elsewhere?

Your change set includes a number of different cctbx sub packages, so the tests required are kind-of nonuniform 😕 sorry

**Comment by dwpaley** [comment]
@pafonine @graeme-winter Thank you both for the comments.

Pavel, there are about 10 methods in xray.structure that construct a new structure from an existing one; all of these forward a bunch of attributes from the old structure to the constructor of the new one. I can go through and add ", wavelength=self.wavelength" to all of these but please confirm that's what you want.

Graeme, based on a conversation with Luc Bourhis it seems smtbx.refine was abandoned at an early stage in favor of the Olex2 gui. Thus I'm not surprised there are no integration tests. I don't think anyone uses it (and I won't either in its current form). But, to make it official I can write a basic integration test for the script and make a new home for it smtbx/command_line/tests. Sound ok?

Thanks
Dan

**Comment by bkpoon** [comment]
@dwpaley Can you pull in the latest changes to `master`? I just cleaned the clutter. That will allow the tests to run. Thanks!

**Comment by bkpoon** [comment]
Also, the `smtbx/command_line/__init__.py` file can just be empty.

**Comment by dwpaley** [comment]
@bkpoon Thanks, there was also some clutter on my end.

@pafonine @graeme-winter I believe all requested changes are done. All the methods in cctbx.xray.structure that construct a copy are now forwarding self.wavelength from the original. Tests for reading the wavelength are added for iotbx.cif, iotbx.shelx and cctbx.xray.structure. There's also a basic integration test for smtbx.refine.

Best,
Dan

**Comment by dwpaley** [comment]
The test of smtbx.refine was leaving behind an output file and thus cluttering up "git status" etc; this is fixed now. Sorry for the profusion of commits and let me know if you'd like me to squash them together. Dan

**Comment by bkpoon** [comment]
The CentOS 8 failure is fine, it's an issue with the conda environment.

**Comment by pafonine** [comment]
If you do selection or deep_copy on xray.structure, then probably you 
want to make sure this isn't lost.

**Comment by dwpaley** [comment]
@pafonine Correct, all the xray.structure methods that make a new copy now pass along the wavelength, including select and deep_copy_scatterers. There are some like cubic_unit_cell_around_centered_scatterers where it seemed unnecessary, but I thought it would be harmless at worst so I included it for those too.

**Comment by bkpoon** [comment]
@dwpaley Do @luc-j-bourhis and @pcxod need to review this?

**Comment by dwpaley** [comment]
I’m not sure. @luc-j-bourhis <https://github.com/luc-j-bourhis> is aware of
the PR, we discussed it by email this week.

**Comment by pafonine** [comment]
ok, sounds good.

**Comment by luc-j-bourhis** [comment]
Hi,

yes, I am aware of this pull request and I did tell Oleg too. I am a bit overwhelmed right now but we'll try to take care of it next week…

Best wishes,

Luc

**Comment by pcxod** [comment]
Hi Luc, thanks for pointing me to this.
Hi Dan, indeed, smtbx refinement inside cctbx never really happened - it is mostly used as a library. There is a number of reasons for that. One in particular is that Olex2 is used as a model builder - and therefore is used to set up the refinement (there is also a command line version for that). But the library itself is being developed quite extensively - I currently have a cloned repository that has numerous changes (again...) - it however can be merged in with master without problems (have not any tests yet, one day I will make a pull request...).  But if you are going to contribute into smtbx - please do try to synchronise it with me as there have been a lot of changes - like using non-spherical atomic form factors, refining anharmonic ADP motion and other stuff - last week I added fp/fdp refinement in (constrained by scatterer type or otherwise). And may be you can help me with merging it all in :).
Cheers, Oleg.

**Comment by dwpaley** [comment]
@pcxod thanks for clarifying. My reason for working on this was to add fp,fdp refinement, that work is here: https://github.com/dwpaley/cctbx_project/tree/smtbx-fpfdprefinement and looks very similar to yours although I omitted constrained groups of fp/fdps. I should have checked with you sooner!

I have further plans as well involving inelastic scattering factors so maybe I should contact you offline to coordinate...

Best,
Dan

**Comment by bkpoon** [comment]
@pcxod @luc-j-bourhis So this is okay to be merged?

**Comment by pcxod** [comment]
AS long as it does not break anything - yes, pls

**Pull request merged**
