### PR TITLE
Dna vs rna ribbons

### PR DESCRIPTION
**Pull request by russell-taylor**
Properly configures ksdssp and includes it in all builds.

Handles combination of DNA and RNA within the same file in ribbons code by swapping the DNA but not the RNA.

Uses secondary-structure information found in the original PDB file if it is there rather than recomputing it.

### CODE REVIEW

**Comment by russell-taylor** [comment]
@bkpoon Any idea why my rebase on master pulled in all of the commits in my history above? I did the rebase on my machine and then pushed to the branch. Is this going to be a problem if I do a squash merge?

**Comment by russell-taylor** [comment]
@nwmoriarty @bkpoon This is failing a test, but doing so in files that I didn't touch. The error message is below. It may be that something about including the ksdssp module caused this the fire when not under Phenix, exposing a dependency that causes CCTBX tests to file. In any case, this is beyond my ability to fix.

Should I go ahead and do the merge, or can you point me in the right direction to fix it?

Thanks,
Russ

```
libtbx.python "/Users/runner/work/1/modules/cctbx_project/iotbx/regression/secondary_structure/tst_annotation.py" [FAIL] 3.1s
  Time:  3.09
  Return code: 1
  OKs: 0
/Users/runner/work/1/miniforge/envs/py37/lib/python3.7/site-packages/junit_xml/__init__.py:270: DeprecationWarning: Testsuite.to_file is deprecated. It will be removed in version 2.0.0. Use function to_xml_report_file
  DeprecationWarning,
  Standard error:
    Traceback (most recent call last):
      File "/Users/runner/work/1/modules/cctbx_project/iotbx/regression/secondary_structure/tst_annotation.py", line 2104, in <module>
        tst_filter_sheets_with_long_hbonds()
      File "/Users/runner/work/1/modules/cctbx_project/iotbx/regression/secondary_structure/tst_annotation.py", line 1669, in tst_filter_sheets_with_long_hbonds
        ann.filter_sheets_with_long_hbonds(hierarchy=h)
      File "/Users/runner/work/1/modules/cctbx_project/iotbx/pdb/secondary_structure.py", line 938, in filter_sheets_with_long_hbonds
        from mmtbx.secondary_structure.ss_validation import gather_ss_stats
      File "/Users/runner/work/1/modules/cctbx_project/mmtbx/secondary_structure/ss_validation.py", line 19, in <module>
        from phenix.pdb_tools.phi_psi_2_data import phi_psi_2_mask_class
    ModuleNotFoundError: No module named 'phenix'

```

**Comment by nwmoriarty** [comment]
Russell

This is Oleg's code so I'll cc him for comment.

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Email : ***@***.***
Web  : CCI.LBL.gov
ORCID : orcid.org/0000-0001-8857-9464

**Comment by nwmoriarty** [comment]
Hi Nigel, Russ,

I'm fine with this test failing at the moment, because apparently the
functionality depends on
phenix.pdb_tools.phi_psi_2_data

At the same time, Nigel, was there a particular reason for it to be in
Phenix or we can move it to CCTBX instead? I'm using it in secondary
structure validation which is in CCTBX and would vote for the move.

Best regards,
Oleg Sobolev.

**Comment by nwmoriarty** [comment]
Works for me!

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Email : ***@***.***
Web  : CCI.LBL.gov
ORCID : orcid.org/0000-0001-8857-9464

**Pull request merged**
