### PR TITLE
Chirality restraint for smtbx

### PR DESCRIPTION
**Pull request by pascal22p**
This is an addition for smtbx to the current chirality restraint. I also added sym_ops. 

These modifications are a bit more invasive than RIGU. I run the tests where the restraint was present and they are alright.

### CODE REVIEW

**Comment by pascal22p** [comment]
If there is no more objections, could anyone merge this?

**Comment by olegsobolev** [comment]
If I understand correctly, this pull request adds symmetry-aware chirality restraint. First and foremost I'd like to say that this functionality is welcomed. Do you have any plans to make other restraints symmetry-aware?

I'll look at the code closer when the following is fixed:

1. Bunch of extra output everywhere likely coming from chirality.h:280
```
-6.522 2.038 2.831
-7.656 2.923 3.155
-5.241 2.537 3.427
```
run 
mmtbx/command_line/geometry_minimization.py <any pdb> 
to see. Strange only phenix_regression tests catch it, but I'm not sure about this sinse huge amount of extra output crashed our testing system at the end. For those who curious:
```
Tests finished. Elapsed time: 900.73s

Traceback (most recent call last):
  File "/net/anaconda/raid1/olegs/phenix_test/build/../modules/phenix_regression/command_line/test_all_parallel.py", line 53, in <module>
    run()
  File "/net/anaconda/raid1/olegs/phenix_test/build/../modules/phenix_regression/command_line/test_all_parallel.py", line 50, in run
    return run_tests_parallel.run(cmdargs + sys.argv[1:])
  File "/net/anaconda/raid1/olegs/phenix_test/modules/cctbx_project/libtbx/command_line/run_tests_parallel.py", line 96, in run
    max_time=params.max_time)
  File "/net/anaconda/raid1/olegs/phenix_test/modules/cctbx_project/libtbx/test_utils/parallel.py", line 283, in __init__
    write_JUnit_XML(self.results, "output.xml")
  File "/net/anaconda/raid1/olegs/phenix_test/modules/cctbx_project/libtbx/test_utils/parallel.py", line 196, in write_JUnit_XML
    ts.to_file(f, [ts], prettyprint=True, encoding="utf-8")
  File "/net/anaconda/raid1/olegs/phenix_test/base/lib/python2.7/site-packages/junit_xml/__init__.py", line 241, in to_file
    test_suites, prettyprint=prettyprint, encoding=encoding)
  File "/net/anaconda/raid1/olegs/phenix_test/base/lib/python2.7/site-packages/junit_xml/__init__.py", line 227, in to_xml_string
    xml_string = xml.dom.minidom.parseString(xml_string)
  File "/net/anaconda/raid1/olegs/phenix_test/base/lib/python2.7/xml/dom/minidom.py", line 1928, in parseString
    return expatbuilder.parseString(string)
  File "/net/anaconda/raid1/olegs/phenix_test/base/lib/python2.7/xml/dom/expatbuilder.py", line 940, in parseString
    return builder.parseString(string)
  File "/net/anaconda/raid1/olegs/phenix_test/base/lib/python2.7/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
OverflowError: size does not fit in an int
```

2. Also no tests except for mmCIF output. Finite difference? Correct gradient values, deltas, residuals etc... Bunch of examples for another restraints. The tests also serve as usage examples for other developers, that's why they are very important.

**Comment by pascal22p** [comment]
> If I understand correctly, this pull request adds symmetry-aware chirality restraint. First and foremost I'd like to say that this functionality is welcomed. Do you have any plans to make other restraints symmetry-aware?

It adds the chirality restraint altogether to smtbx which was missing. the symmetry bit is extra. No, no plan for more I am afraid.

> 
> I'll look at the code closer when the following is fixed:
> 
>     1. Bunch of extra output everywhere likely coming from chirality.h:280
> 
> 
> ```
> -6.522 2.038 2.831
> -7.656 2.923 3.155
> -5.241 2.537 3.427
> ```
> 

fixed in 8e2b5d1

**Comment by pascal22p** [comment]
Tests are already in tst_ext.py, exercise_chirality. Do you want me to duplicate these with the symmetry operator used?

**Comment by olegsobolev** [comment]
> Tests are already in tst_ext.py, exercise_chirality.

These tests do not test your new overloaded proxy constructors because they don't use sym_ops. And all the rest sym_ops logic you introduced. 
> Do you want me to duplicate these with the symmetry operator used?

Yes. See exercise_angle() there for example.

**Comment by pcxod** [comment]
Superseded by #295

**Pull request closed without merging**
