### PR TITLE
Define python dependencies in libtbx_config

### PR DESCRIPTION
**Pull request by ndevenish**
At the moment python dependency resolution is done and installed at the `libtbx.refresh` stage, via each packages `libtbx_refresh.py`. This can cause problems if packages cannot be installed e.g. on an offline node, or if the global site-packages folder is read-only. 

Having the configuration inside the `libtbx_refresh.py` file means that the only way to tell what's required is by manual inspection or parsing the output of refresh. And, since each package only knows about it's own requirements, leaves the potential of conflicting requirements going unnoticed.

This patch moves the listing of requirements to the libtbx_config configuration file, where the other module dependencies are specified, which means that it can be easily read before running libtbx.refresh - dependencies can be worked out before you have a fully running and configured distribution, and merged before installation.

This would help some of the issues discussed in #151.

Also, added a utility, `libtbx.show_python_dependencies`, to list/inspect python dependencies in an existing environment. Here's what the standard output looks like where I've converted the `dxtbx`, `dials` (sample commit https://github.com/ndevenish/dials-fork/commit/6e9f736c0d90bcd2f637f28f97398e87b8f4df21) and `xia2` refresh scripts:

image

By passing the `--all` flag you can get a list of all requirements suitable for e.g. building an offline list:
```
$ libtbx.show_python_dependencies --all
blosc Jinja2 'mock>=2.0' msgpack orderedset 'procrunner>=0.6' 'pytest>=3.1,>=3.6' scikit_learn[alldeps] scipy tabulate 'tqdm==4.23.4'
```

### CODE REVIEW

**Comment by graeme-winter** [comment]
This looks like a great idea - I can also see it being very helpful for @bkpoon making conda package updates - having all the dependencies explicit would really help.

**Comment by graeme-winter** [comment]
Will need to merge across the dependency requirement specification for other cctbx packages thoughj e.g. 

```
{
  "modules_required_for_use" : [ "iotbx", "cbflib_adaptbx" ],
  "python_required": [
    "mock>=2.0",
    "pytest>=3.1"
  ],
}
```

for dxtbx - looking at it though these are pretty compact - in fact do other packages even have these?

**Comment by graeme-winter** [comment]
... that would be "no"

```
Grey-Area cctbx_project :( [master] $ grep 'libtbx.pkg_utils.require' */libtbx_refresh.py
dxtbx/libtbx_refresh.py:libtbx.pkg_utils.require('mock', '>=2.0')
dxtbx/libtbx_refresh.py:libtbx.pkg_utils.require('pytest', '>=3.1')
```

**Comment by bkpoon** [comment]
This would be a good opportunity to discuss the design and goals of this functionality. It looks like this was originally added with ea7c2c0513f0787f6362dd45a182d908a27e5610 in September 2017 and there was not much discussion about its purpose. Since this affects everyone and has caused issues in the past as stated by @ndevenish (#151) and also on the [cctbxbb](http://phenix-online.org/pipermail/cctbxbb/2018-April/001869.html), I think we should try to prevent future problems by laying out the problem to be solved and the overall plan.

Here is a list of concerns that I have with this feature.
- My main concern is that this seems to only work for Python dependencies and possibly only pure Python dependencies. We have both Python and non-Python dependencies and some are related (e.g. `libhdf5` and `h5py`, or `mpi4py` and MPI libraries). I think all dependencies should all be handled in a consistent manner. We currently have all the dependencies defined in [`package_defs.py`](../blob/master/libtbx/auto_build/package_defs.py). The file is hand-curated and built regularly to ensure that all the dependencies are compatible. For `conda`, I have combined all the dependencies into a [single file](
https://github.com/cctbx/conda_build/blob/master/cctbx_dependencies/meta.yaml) as well, with `conda` handling the dependency resolution.
- Does this cause each directory to have it's own list of dependencies? And only for packages installable by `pip`? Where would non-Python dependencies go?
- What about duplicates? In `dxtbx` and `dials`, there are duplicated entries for `mock` and `pytest`. Since `dials` depends on `dxtbx`, should those dependencies be defined just for `dxtbx`?
- There seems to be [`libtbx.install`](../blob/master/libtbx/command_line/install.py) command that looks like a wrapper for `pip` but is also used to handle dependencies? I see the header files for `msgpack` but isn't that a duplicated entry in bootstrap.py?
- Will `pip` be used for dependency resolution? It looks like `pip install` would need to be run with the `-r` flag as noted in the [documentation](https://pip.pypa.io/en/stable/user_guide/#requirements-files).

**Comment by graeme-winter** [comment]
@bkpoon the idea of this is to declare explicitly requirements, which seems like _a good idea_ 

One challenge we face is adding modules where we have local dependencies not satisfied by https://github.com/cctbx/cctbx_project/blob/master/libtbx/auto_build/package_defs.py - i.e. dependencies in local modules which are not distributed. This was the basis of the 2017 work. 

Each directory _may_ have dependencies (i.e. not must) but if not, they should probably be declared in https://github.com/cctbx/cctbx_project/blob/master/libtbx/auto_build/package_defs.py 

Non Python dependencies are a different problem but presumably would have to go through the existing mechanisms - we are not trying to solve all problems here just make one thing better. Duplicates are fine, since multiple modules may share dependencies and they will all be satisfied anyway. Pip can be used for dependencies, but if they are all already there then nothing will happen, so no harm will be done.

Other than "this does not solve all the problems" I do not seem what _harm_ is done by this? Does it make anything actually worse.

**Comment by graeme-winter** [comment]
Concern reported by @phyy-nx / @bkpoon that this is turning into a package manager - with good reason? Discuss.

**Comment by graeme-winter** [comment]
TBH I think having explicit per-module dependencies is a good thing, since it avoids one static dependencies-for-all-things file somewhere. But that's my perspective. Internal Diamond examples helpful here.

**Comment by graeme-winter** [comment]
Example from diamond...
```
from __future__ import absolute_import, division, print_function

import ast
import imp
import pkgutil

import dlstbx.services
import libtbx.pkg_utils

try:
  from dlstbx.util.version import dlstbx_version
  print(dlstbx_version())
except Exception:
  pass

libtbx.pkg_utils.require('mock', '>=2.0')
libtbx.pkg_utils.require('pytest', '>=3.1')
libtbx.pkg_utils.require('ispyb', '>=4.13,<4.14')
libtbx.pkg_utils.require('workflows', '>=1.1')
libtbx.pkg_utils.require('drmaa')
libtbx.pkg_utils.require('junit_xml')
libtbx.pkg_utils.require('colorama') # is still used in one place
libtbx.pkg_utils.require('procrunner', '>=0.8.0')
libtbx.pkg_utils.require('zocalo', '>=0.5.1')

# Eiger stream work, SCI-7786
libtbx.pkg_utils.require('confluent-kafka')
libtbx.pkg_utils.require('msgpack')
libtbx.pkg_utils.require('pyzmq')
```

**Comment by graeme-winter** [comment]
Many things in here which are not in standard bootstrap build, and also don’t belong in there either...

**Comment by ndevenish** [comment]
libtbx is already a package manager, for tbx modules. It allows adding arbitrary modules and manages dependencies between them, except that it's not a very good or complete package manager - some class of dependencies (binary, python) are impossible to determine before running the code, and up until the changes in ea7c2c0513f0787f6362dd45a182d908a27e5610, impossible to specify except centrally in the hard-to-edit `install_base_packages.py`. It has lots of other issues that we jump through hoops to work around but those are a separate topic.

Centrally specifying packages doesn't work for us for e.g. diamond-internal packages, with dependencies that don't belong in the central installation. Plus, central lists make it hard to connect requirements with where they came from and what they are for (the dials dependencies, for a start, are for a completely different repository).

The previous `pkg_utils.require` changes let us manage our installations and add/dependencies without having to edit the central dependency lists, but still the problem that it's impossible to tell what the dependencies are without actually configuring and running the packages, and It also made it slightly harder for you to tell what the requirements were (by definition, allowing change at all makes this harder) which you ran into with your offline source-based installations.

All this does is make dependencies easier to write, and easier to introspect. It's the opposite of making libtbx into a package manager - because it deliberately makes it easier to rely on external tools for determining environment.

As pointed out above, this doesn't handle other binary dependencies. Adding binary dependencies is a much bigger deal with more consequences and more difficult cost/benefit decisions.

**Comment by bkpoon** [comment]
I'm getting this traceback when trying to configure `libtbx` by itself.
```
Traceback (most recent call last):
  File "../modules/cctbx_project/libtbx/configure.py", line 34, in <module>
    if not run():
  File "../modules/cctbx_project/libtbx/configure.py", line 28, in run
    import libtbx.env_config
  File "/dev/shm/bkpoon/software/a/modules/cctbx_project/libtbx/env_config.py", line 21, in <module>
    import libtbx.pkg_utils
  File "/dev/shm/bkpoon/software/a/modules/cctbx_project/libtbx/pkg_utils.py", line 12, in <module>
    import libtbx.load_env
  File "/dev/shm/bkpoon/software/a/modules/cctbx_project/libtbx/load_env.py", line 5, in <module>
    libtbx.env = libtbx.env_config.unpickle()
AttributeError: 'module' object has no attribute 'env_config'
```
I have a `modules` directory with just `cctbx_project`. Then I run
1) `git checkout -b ndevenish-python_config master` (GitHub CLI instructions)
2) `git pull https://github.com/ndevenish/cctbx_project-fork.git python_config` (GitHub CLI instructions)
3) Make a `build` directory and copy an existing `base` directory to the same level as the `modules` directory.
4) In the `build` directory, run `../base/bin/python ../modules/cctbx_project/libtbx/configure.py libtbx`

I am not fully aware of the history of CCTBX, but the configuration step in `libtbx` is not designed to be a general package manager. It is based on SCons (https://scons.org), which is like `make`. And like `make`, usually only the dependencies among the source code, in our case, the `*tbx` modules, are described. External dependencies were not included, presumably since there were not many when CCTBX first started.

Looking at the implementation of `libtbx.pkg_utils.require` and the `resolve_python_module_dependencies` function in this pull request, are you checking each line separately? For example, in
```
libtbx.pkg_utils.require('mock', '>=2.0')
libtbx.pkg_utils.require('pytest', '>=3.1')
```
is `mock` checked first, and then `pytest` is checked separately? This pull request mentions "python dependency resolution," but what is the intended behavior? Checking dependencies one at at time with `pip` is not the same as checking them all at once as described in the `pip` documentation [link](https://pip.pypa.io/en/stable/user_guide/#requirements-files)

Would it make sense to construct a `requirements.txt` file in your Diamond-specific packages and run `pip install -r requirements.txt`?

**Comment by ndevenish** [comment]
> I'm getting this traceback when trying to configure `libtbx` by itself.

Thanks, there was a simple import-loading-order problem that I've fixed.

Regarding this commit:

- This doesn't add any stages of install that aren't already done
- This actually does do some dependency merging whereas conflicts just competed before
- This is literally just making the metadata easier to manage
- We discussed this nine months ago and response was positive https://docs.google.com/document/d/1oRXECbX5znnsoL3nLaDr0jqXP-Yh6mFCAx04ftvYr6c/edit#bookmark=id.w47xxbi2zo47

**Comment by graeme-winter** [comment]
From where I am sat, it looks like the issues here are resolved and - from what I can tell - the changes should be invisible for the vast majority of cctbx developers.

**Pull request merged**
