### PR TITLE
Change required to fix e.g. dials.image_viewer on Linux

### PR DESCRIPTION
**Pull request by dagewa**
As suggested by @dermen in https://github.com/dials/dials/issues/1442#issuecomment-709530168, this fixes the `dials.image_viewer` for me on Linux at least (ignoring 7 `wxPyDeprecationWarning`s)

### CODE REVIEW

**Comment by dagewa** [comment]
Understood this is merely a workaround, but I need the image viewer

**Comment by rjgildea** [comment]
Confirmed this works (kind of) on my mac build (with Python version 3.6.10):

On master:
```
$ dials.python --version
Python 3.6.10

$ dials.image_viewer $(dials.data get -q centroid_test_data)/*.cbf
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = <image files>
}

/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py:158: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  kind=wx.ITEM_NORMAL,
/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py:178: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  kind=wx.ITEM_NORMAL,
/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py:207: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  kind=wx.ITEM_NORMAL,
/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py:215: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  kind=wx.ITEM_NORMAL,
/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/slip_viewer/pyslip.py:189: wxPyDeprecationWarning: Call to deprecated item EmptyBitmap. Use :class:`wx.Bitmap` instead
  self.buffer = wx.EmptyBitmap(width, height)
/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/slip_viewer/tile_generation.py:403: wxPyDeprecationWarning: Call to deprecated item EmptyImage. Use :class:`Image` instead.
  wx_image = wx.EmptyImage(256, 256)
Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx_py3/build/../../cctbx/modules/dials/command_line/image_viewer.py", line 222, in <module>
    run()
  File "/Users/rjgildea/software/cctbx_py3/build/../conda_base/python.app/Contents/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/Users/rjgildea/software/cctbx_py3/build/../../cctbx/modules/dials/command_line/image_viewer.py", line 218, in run
    show_image_viewer(params=params, reflections=reflections, experiments=experiments)
  File "/Users/rjgildea/software/cctbx_py3/build/../../cctbx/modules/dials/command_line/image_viewer.py", line 168, in show_image_viewer
    wrapper.display(experiments=experiments, reflections=reflections)
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_wrap.py", line 83, in display
    self.frame.load_image(chooser_wrapper(imagesets[0], 0))
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 553, in load_image
    show_untrusted=show_untrusted,
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/slip_viewer/frame.py", line 401, in load_image
    self.OnShowSettings(None)
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 581, in OnShowSettings
    pos=(x_start, y_start),
  File "/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py", line 1681, in __init__
    super().__init__(*args, **kwds)
  File "/Users/rjgildea/software/cctbx/modules/cctbx_project/rstbx/viewer/frame.py", line 363, in __init__
    panel = SettingsPanel(self, -1)
  File "/Users/rjgildea/software/cctbx/modules/cctbx_project/rstbx/viewer/frame.py", line 397, in __init__
    grid = wx.FlexGridSizer(cols=2, rows=2)
TypeError: Please report this error to dials-support@lists.sourceforge.net: FlexGridSizer(): arguments did not match any overloaded call:
  overload 1: 'rows' is not a valid keyword argument
  overload 2: 'rows' is not a valid keyword argument
  overload 3: not enough arguments
  overload 4: not enough arguments
```

With this PR:

```
$ git checkout recover-image-viewer
Switched to branch 'recover-image-viewer'
Your branch is up to date with 'origin/recover-image-viewer'.

$ dials.image_viewer $(dials.data get -q centroid_test_data)/*.cbf
DIALS (2018) Acta Cryst. D74, 85-97. https://doi.org/10.1107/S2059798317017235
The following parameters have been modified:

input {
  experiments = <image files>
}

/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py:158: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  kind=wx.ITEM_NORMAL,
/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py:178: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  kind=wx.ITEM_NORMAL,
/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py:207: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  kind=wx.ITEM_NORMAL,
/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/spotfinder_frame.py:215: wxPyDeprecationWarning: Call to deprecated item. Use :meth:`AddTool` instead.
  kind=wx.ITEM_NORMAL,
/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/slip_viewer/pyslip.py:189: wxPyDeprecationWarning: Call to deprecated item EmptyBitmap. Use :class:`wx.Bitmap` instead
  self.buffer = wx.EmptyBitmap(width, height)
/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/slip_viewer/tile_generation.py:403: wxPyDeprecationWarning: Call to deprecated item EmptyImage. Use :class:`Image` instead.
  wx_image = wx.EmptyImage(256, 256)
/Users/rjgildea/software/cctbx/modules/dials/util/image_viewer/slip_viewer/tile_generation.py:399: wxPyDeprecationWarning: Call to deprecated item EmptyImage. Use :class:`Image` instead.
  wx_image = wx.EmptyImage(w, h)
```

However, the settings panel is a bit funky:
Screenshot 2020-10-20 at 11 39 57

**Comment by dermen** [comment]
Seems like maybe its to do with the transparency of the rstbx/viewer/frame.py Panel.. Notice there are two Brightness texts, one with colon (from dials/util/image_viewer/spotfinder_frame.py , and the other is coming from cctbx_project/rstbx/viewer/frame.py. Im guessing it matters not what vgap, hgap are, so long as they are present. And maybe in Mac OS the new default is to make the frames transparent ?

**Comment by dermen** [comment]
I guess its a necessary step, so lets merge it in.

**Review by dermen — APPROVED** [review]
I would suggest changing vgap = hgap = 0 (to be in line with whats in dials/util/image_viewer/spotfinder_frame.py).  I can confirm it will still look ok in linux. annd at least it works, sorry I didnt get to this until now! I agree, we need a functioning image viewer

**Comment by dagewa** [comment]
Ok, merging this to get it working on Linux while @ndevenish looks at the macOS fix https://github.com/dials/dials/issues/1442#issuecomment-713758620

**Pull request merged**
