### PR TITLE
Fix scaling of diffuse in diffBragg

### PR DESCRIPTION
**Pull request by mewall**

### CODE REVIEW

**Comment by nksauter** [comment]
@mewall I'm getting a bunch of "maybe-uninitialized" warnings in the code that seem to pertain to the new variable introduced.  I wonder if you could do a little polishing to make sure we don't hit any warnings--thanks.
```
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:313:25: warning: ‘dll’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  313 |     dHH << dhh, dkk, dll;
      |                         ^  
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:251:15: note: ‘dll’ was declared here
  251 |     int dhh, dkk, dll;
      |               ^~~
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:313:19: warning: ‘dkk’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  313 |     dHH << dhh, dkk, dll;
      |                   ^~~
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:251:10: note: ‘dkk’ was declared here
  251 |     int dhh, dkk, dll;
      |          ^~~
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:313:9: warning: ‘dhh’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  313 |     dHH << dhh, dkk, dll;
      |     ~~~~^~~~~~~~
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:251:5: note: ‘dhh’ was declared here
  251 |     int dhh, dkk, dll;
      |     ^~~
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:318: warning: ‘num_laue_mats’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  318 |     Kokkos::parallel_for(
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:250:5: note: ‘num_laue_mats’ was declared here
  250 |     int num_laue_mats;
      |     ^~~~~~~~~~~~~
```

**Comment by mewall** [comment]
@nksauter These are all old variables, I suspect these warnings aren't new? I'll take a look though and see whether there's something to be done.

________________________________
From: nksauter ***@***.***>
Sent: Wednesday, May 24, 2023 7:52:48 PM
To: cctbx/cctbx_project
Cc: Wall, Michael E; Mention
Subject: [EXTERNAL] Re: [cctbx/cctbx_project] Fix scaling of diffuse in diffBragg (PR #879)


@mewall<https://urldefense.com/v3/__https://github.com/mewall__;!!Bt8fGhp8LhKGRg!F1c4RqwlaaREOYjgZ0j4W95c_o0Ag0RByMtuByIzL-ALP0ZykBehaudLG0_6w3BothJIZygXte32Wda5HhQNLpsd$> I'm getting a bunch of "maybe-uninitialized" warnings in the code that seem to pertain to the new variable introduced. I wonder if you could do a little polishing to make sure we don't hit any warnings--thanks.

/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:313:25: warning: ‘dll’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  313 |     dHH << dhh, dkk, dll;
      |                         ^
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:251:15: note: ‘dll’ was declared here
  251 |     int dhh, dkk, dll;
      |               ^~~
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:313:19: warning: ‘dkk’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  313 |     dHH << dhh, dkk, dll;
      |                   ^~~
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:251:10: note: ‘dkk’ was declared here
  251 |     int dhh, dkk, dll;
      |          ^~~
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:313:9: warning: ‘dhh’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  313 |     dHH << dhh, dkk, dll;
      |     ~~~~^~~~~~~~
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:251:5: note: ‘dhh’ was declared here
  251 |     int dhh, dkk, dll;
      |     ^~~
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:318: warning: ‘num_laue_mats’ may be used uninitialized in this function [-Wmaybe-uninitialized]
  318 |     Kokkos::parallel_for(
/dev/shm/sauter/sim/modules/cctbx_project/simtbx/diffBragg/src/diffBragg_kokkos_kernel.cpp:250:5: note: ‘num_laue_mats’ was declared here
  250 |     int num_laue_mats;
      |     ^~~~~~~~~~~~~

**Comment by mewall** [comment]
@nksauter


Also this is happening in some source code that wasn't touched in the PR...


Can we merge and I can address this as a separate issue?

________________________________

**Comment by nksauter** [comment]
@mewall as you like.

**Pull request merged**
