### PR TITLE
Implementation of TLS-analysis in c++

### PR DESCRIPTION
**Pull request by nicholas-pearce**
Reimplementation of the tis-analysis of mmtbx/tls/analysis.py in c++ for speed. Compares at ~0.6s in python to 0.002s in c++. Tests implemented against the original mmtbx/tls/analysis.py. Also identified and fixed an error in the original mmtbx/tls/analysis.py.

This is my first commit to the cctbx so you may wish to check this code more thoroughly than you might do for others -- feedback is appreciated to make sure I'm doing things properly.

### CODE REVIEW

**Comment by Anthchirp** [comment]
Hi Nick,

obviously can't comment on the main point of the mmtbx changes but just two comments.

You have two merge commits as part of your pull request. Could you please get rid of them? The easiest and best way to do this would be to simply rebase the pull request branch on top of cctbx:master. I've tested it, and it should works cleanly. (In future you may find it useful to create separate branches for pull requests, so what you do on your master branch doesn't affect the pull request - currently it does)

The other comment is that it may be of interest to look into using pytest for tests, although I think mmtbx does not support those yet. But that would allow you to get rid of helper constructs such as
```python
try:
  (...)
except Exception as e:
  print e
  raise
```
In case the mmtbx folks are interested in enabling pytests - [here is how](https://github.com/dials/dials/wiki/Why-pytest%3F#enabling-pytests-for-a-cctbx-module).

**Comment by nicholas-pearce** [comment]
Hi,

I will try to rebase. Will find instructions on the google.

I am happy (and would prefer!) to write pytests. Your instructions are pretty good for doing so, so I think I will. The try except that you show is actually from trying to debug the test (there was also a bug in the original code I was reimplementing) and I should remove it.

**Comment by Anthchirp** [comment]
Instructions to rebase should be approximately
```bash
git remote -v
# You should have two entries here, 'origin' pointing to your private repository and 'upstream' pointing to the original cctbx repository

git checkout master # your master branch
git rebase upstream/master # do the rebase
git log -6 # check if results are sensible
git push -f # update pull request
```

**Comment by pafonine** [comment]
> The other comment is that it may be of interest to look into using 
> pytest for tests, 

I wrote the original code that Nick modified, I still occasionally work 
on it and I maintain the code and tests. I won't support it if it starts 
using a different testing method.

Pavel

**Comment by nicholas-pearce** [comment]
Ok. To be clear I was not suggesting re-writing your tests, only my new test. 

I can therefore...
a) Leave my new test in the libtbx framework.
b) re-write my new test in pytest and then make them libtbx-compatible (as detailed in Markus' link).

I have a mild preference for b) because I am more familiar with pytest. However, if you would prefer a), I am happy with that and I will leave as is. Which would you like me to do?

**Comment by pafonine** [comment]
Nick,

a very comprehensive set of tests for this code is located here:

mmtbx/regression/tls

So if your C++ implementation mirrors the original Python implementation 
then it must pass these tests.

All the best,
Pavel

**Comment by pafonine** [comment]
P.S.:
If C++ and Python implementations are redundant then one needs to be 
removed.
Pavel

**Comment by nicholas-pearce** [comment]
Yes, I agree.

I will replace the python implementation with the c++ one and ensure all tests run correctly with the c++ implementation. I will then issue another pull request.

Thanks,
Nick

**Pull request closed without merging**
