### PR TITLE
Update Sphinx to version 1.6.7

### PR DESCRIPTION
**Pull request by Anthchirp**
Update Sphinx 1.4.9 (Nov. 2016) to 1.6.7 (Feb 2018).

1.7 is too large a jump and currently causes issues with building the documentation. So this would be a stepping stone so all sphinx users can take note of deprecation warnings.

You can test without bootstrapping with ```libtbx.pip install sphinx==1.6.7``` and revert with ```libtbx.pip install sphinx==1.4.9```.

### CODE REVIEW

**Comment by ndevenish** [comment]
I'm all for this; 1.5 and 1.6 add some features (amongst others) that make it much easier to extract [subsections](http://www.sphinx-doc.org/en/stable/markup/code.html#directive-literalinclude) of source files.

**Comment by ndevenish** [comment]
https://github.com/dials/dials/commit/79500a7cefbbb25454284586a20ab0e7bb61d195 appears to be all that is required for the warnings to go away and for 1.7.x compatibility, at least on our side.

So, I'd propose just jumping straight to 1.7.2, as long as everything else is compatible - `libtbx.pip install sphinx==1.7.2` (I don't know if phenix uses sphinx, and how to build it anyway).

**Comment by Anthchirp** [comment]
Meeting 2018-04-12: Update to 1.6.x or most recent version possible as long as cctbx.github.io builds without issue.

**Comment by ndevenish** [comment]
I've fixed the conflicts, so updated to the current version (1.7.2) in 4183fde63169de5d1c2f2ae9b8d7712207b44b68. Thanks all.

**Pull request closed without merging**
