### PR TITLE
Use stable sort by default

### PR DESCRIPTION
**Pull request by Anthchirp**
following #288.

Performance impact appears to be, if there is any at all, on the positive side.

### CODE REVIEW

**Comment by Anthchirp** [comment]
image

**Comment by phyy-nx** [comment]
Are these numbers test timings?

**Comment by Anthchirp** [comment]
Ah yes, units are seconds as reported by bash _time_, running basically
```bash
for m in libtbx cctbx iotbx scitbx rstbx dxtbx; do
  for round in 1 2 3 4 5; do
    mkt # run in a new temporary directory
    time libtbx.run_tests_parallel module=${m} nproc=1
  done
done
```

**Comment by phyy-nx** [comment]
Hi all, I ran the phenix tests and one of them doesn't pass on the stablesort branch, but does pass on master.  Specifically phenix_regression/wizards/command_line_misc_tests/test_hyss/tst_hyss.py.

I'll be in touch with our hyss experts about what is going on, but I don't think we can merge just yet.  Thanks,
-Aaron

**Comment by graeme-winter** [comment]
@phyy-nx interesting - the stable sort main difference is predictable behaviour - unstable sorting obviously does not have this - so very surprising that hyss somehow depends on that 🤔

I suspect that this is a case where the change unmasks another issue, rather than the change itself causing the problem (or the test is not optimally written?)

**Comment by phyy-nx** [comment]
@terwill has fixed the test.  I think we are ok to merge.

**Comment by rjgildea** [comment]
The following commit should also have been included in this pull request:
https://github.com/cctbx/cctbx_project/commit/4354713150bd0c8aa9e1a375bc79e0fa7c7d75c1

**Pull request merged**
