### PR TITLE
Output esd's of fp and fdp in smtbx.anom_refine

### PR DESCRIPTION
**Pull request by dwpaley**
This just adds esd's to the output of smtbx.anom_refine. I don't know why there would be any objection but I will leave this PR here for a couple days to be sure. After that @bkpoon I'm happy to merge it in myself if it's ok with you.

### CODE REVIEW

**Comment by dwpaley** [comment]
This is pretty weird, on Ubuntu 16.04 the refined parameters are correct but the esds are all 0. I'll take a look.

**Comment by dwpaley** [comment]
Ok. The problem is in scitbx.lstbx.levenberg_marquardt_iterations:

```
    while self.n_iterations < self.n_max_iterations:
      a.matrix_packed_u_diagonal_add_in_place(self.mu)
      objective = self.non_linear_ls.objective()
      g = -self.non_linear_ls.opposite_of_gradient()
      self.non_linear_ls.solve()
      if self.had_too_small_a_step(): break
      self.n_iterations += 1
      [...]
      self.non_linear_ls.build_up()
```

If this hits the stopping criterion based on step size, it breaks in the middle of the cycle and leaves self.non_linear_ls holding the solution of the normal equations after modifying with mu (I guess a damping parameter?) Then the covariance_matrix method in smtbx/refinement/least_squares.py uses that solution:

```
      if not self.step_equations().solved:
        self.solve()
```

If I run tst_commandline_anomrefine.py with fewer refinement cycles, the test will pass, but I still see this as a problem. One or both of the following would help:

(1) `levenberg_marquardt_iterations.do()` always finishes the current cycle:

```
    final_cycle = False
    while self.n_iterations < self.n_max_iterations and not final_cycle:
      a.matrix_packed_u_diagonal_add_in_place(self.mu)
      objective = self.non_linear_ls.objective()
      g = -self.non_linear_ls.opposite_of_gradient()
      self.non_linear_ls.solve()
      if self.had_too_small_a_step(): final_cycle = True
      self.n_iterations += 1
      [...]
      self.non_linear_ls.build_up()
```

(2) `ls.covariance_matrix` always calls `self.build_up()` and `self.solve()`. Then it's no longer confused by junk left by a previous cycle.

Seems like both of these would be helpful. @bkpoon @pcxod any thoughts?

**Comment by dagewa** [comment]
> Ok. The problem is in scitbx.lstbx.levenberg_marquardt_iterations:

It has been ages since I looked at similar code, but something looked familiar and I wondered if the way this is arranged in DIALS helps?
https://github.com/dials/dials/blob/6a1395cfda942eba11c3cec7f3101fa431ff9a00/algorithms/refinement/engine.py#L989-L992

**Comment by dwpaley** [comment]
Thanks, David. I'll modify this test with fewer iterations to avoid hitting had_too_small_a_step, and open a separate issue for the L.-M. problem.

**Comment by dwpaley** [comment]
@bkpoon Ok for me to merge this in? The tests pass except for the centos8 thing about endianness which I assume is unrelated to this code.

**Comment by bkpoon** [comment]
@dwpaley Looks good to me, so feel free to merge. The CentOS 8 thing is a conda environment with specific versions that do not work on CentOS 8. The latest one from #409 will work. Your tests have been passing on CentOS 8 in the new environments. There has been some instability, with [tst_commandline_anomrefine.py](https://dev.azure.com/cctbx/cctbx_project/_test/analytics?definitionId=2&contextType=build) (passes ~97% of the time), but the minimizer issue could be the cause. Thanks!

**Comment by dwpaley** [comment]
Thanks, @bkpoon. If you think of it, I'd like to see an example of the failed test. It worries me a bit because it's already testing approx_equal with a pretty generous tolerance.

**Comment by bkpoon** [comment]
Here's a snippet from the log output from this [build](https://dev.azure.com/cctbx/cctbx_project/_build/results?buildId=4530&view=logs&j=c64f1695-528d-57c9-86a2-a2f39f316edd&s=ff05ad62-bb9a-53b6-ce9f-72f329a63e7c). You'll have to scroll down to the Ubuntu 16.04 builds for Python 3.7 and 3.8. They pass on Attempt 2.

```
2020-04-29T06:05:12.8469571Z Error: the following jobs returned non-zero exit codes or suspicious stderr output:
2020-04-29T06:05:12.8469965Z 
2020-04-29T06:05:12.8470527Z libtbx.python "/__w/1/modules/cctbx_project/smtbx/regression/tst_commandline_anomrefine.py" [FAIL] 4.2s
2020-04-29T06:05:12.8470928Z   Time:  4.21
2020-04-29T06:05:12.8471186Z   Return code: 1
2020-04-29T06:05:12.8471603Z   OKs: 0
2020-04-29T06:05:12.8471928Z   Standard error:
2020-04-29T06:05:12.8472255Z     Traceback (most recent call last):
2020-04-29T06:05:12.8472735Z       File "/__w/1/modules/cctbx_project/smtbx/regression/tst_commandline_anomrefine.py", line 28, in <module>
2020-04-29T06:05:12.8473141Z         run()
2020-04-29T06:05:12.8473548Z       File "/__w/1/modules/cctbx_project/smtbx/regression/tst_commandline_anomrefine.py", line 24, in run
2020-04-29T06:05:12.8474034Z         assert out == result, "{} | {}".format(result, out)
2020-04-29T06:05:12.8474731Z     AssertionError: data_global | 13000.0 0.152 -0.053 0.744 1.303
2020-04-29T06:05:12.8475099Z 
2020-04-29T06:05:12.8475402Z Please verify these tests manually.
2020-04-29T06:05:12.8475638Z 
2020-04-29T06:05:12.8475864Z Summary:
2020-04-29T06:05:12.8476181Z   Tests run                    : 492
2020-04-29T06:05:12.8476529Z   Failures                     : 1
2020-04-29T06:05:12.8476892Z   Warnings (possible failures) : 0
2020-04-29T06:05:12.8477239Z   Known Failures (  7)         : 6
2020-04-29T06:05:12.8477596Z   Known Unstable (  3)         : 0
2020-04-29T06:05:12.8477944Z   Stderr output (discouraged)  : 10
2020-04-29T06:05:12.8478197Z 
2020-04-29T06:05:12.8478474Z See run_tests_parallel_zlog for full output.
2020-04-29T06:05:12.8478760Z 
2020-04-29T06:05:12.8478944Z 
2020-04-29T06:05:12.8479278Z ********************************************************************************
2020-04-29T06:05:12.8479708Z ERROR: 1 TEST FAILURES.  PLEASE FIX BEFORE COMMITTING CODE.
2020-04-29T06:05:12.8480152Z ********************************************************************************
```

**Comment by dwpaley** [comment]
Ok, I see. The test should be more stable in the version I just merged into master. Sorry for any trouble that caused and please let me know if it continues to act up.

**Pull request merged**
