### PR TITLE
Python 3.6 / 2.7 cross-compatibility

### PR DESCRIPTION
**Pull request by nksauter**
**This pull request implements the migration of cctbx_project to Python 3.6 while retaining cross-compatibility with Python 2.7.   All tests within cctbx_project were tested on Centos-6.  Mac OSX 10.11 works, and a few more tests fail on 10.14.  Windows tests are still in the future.  The current work was limited to assuring that the tests pass.  We plan follow-up work to assure that all command-line programs run correctly.**

### Current test results are:

|Test results		|	N_total	|	N_fail	|	N_fail	|	N_fail|
|---------------------|-----------------|----------------|----------------|------------------------|
|                               |                       |(Py3.6, Linux)|	(Py2.7, Linux) |(Py27, master, Linux)|
|boost_adaptbx	|	9	|	1	|	0	|	0	|	
|cctbx			|	138		|4	|	0|		0|
|cma_es		|	1	|	0	|	0	|	0|
|fable		|		9	|	0	|	0	|	0|
|gltbx			|	1		|1	|	0	|	0|
|iotbx			|	107		|4	|	0	|	0|
|libtbx			|	36		|0	|	0	|	0|
|mmtbx			|	369	|	112	|	2	|	2|
|rstbx			|	6	|	0	|	0	|	0|
|scitbx			|	135	|	0	|	0	|	0|
|simtbx			|	3	|	0	|	0	|	0|
|smtbx			|	35	|	3	|	0	|	0|
|spotfinder		|	3	|	0	|	0	|	0|
|TOTAL			|	856	|	125	|	2	|	2|
|||||
|without mmtbx	|	487	|	13	|	0	|	0|

### With regard to certain tests:
1. We specifically ask that developers wait for @phyy-nx to fix the boost_adaptbx test (tst_python_streambuf.py), which will be done after the Py2-> Py3 migration is performed for dxtbx (which is intended to be a future community effort).
2. For smtbx, could @luc-j-bourhis and @pcxod have a look?
3. For iota and prime, could @alyubimov please have a look?
4. For mmtbx, @bkpoon, @nwmoriarty, and @olegsobolev will pursue all the follow up on porting tests to Py3.
5. We’ll be requesting help from @Oeffner for Windows issues.
6. The Berkeley group is currently fixing the remaining tests but this is still a short term work in progress.

### To test this branch, use these commands:

Instructions (use two different working directories for Py2 and Py3):
1. Download sources:	`python bootstrap.py hot update --builder=cctbx`
2. Checkout branch:	`cd modules/cctbx_project; git checkout py3`
2a. Replace the downloaded `bootstrap.py` with a symbolic link to the one in `cctbx_project`:
`cd ../..; rm bootstrap.py; ln -s modules/cctbx_project/libtbx/auto_build/bootstrap.py`
3. Build (deactivate any active conda environment, first)
3a. Python 3 Build:	`python bootstrap.py base build --builder=cctbx --use-conda --python3 --nproc=32`
3b. Python 2 Build:	`python bootstrap.py base build --builder=cctbx --use-conda --nproc=32`
4. Source environment:	`source ./build/setpaths.sh`
5. Run tests:		`python bootstrap.py tests --builder=cctbx --nproc=32`

Note, to check for Python 3 syntax: `libtbx.py_compile_all -v -f` with a Python 3 build

### Specific outcomes:
1. We had to switch to the Boost.Python.numpy interface (dropping the numeric interface) to get things working on Python 3. We will be making additional changes to get support for more recent versions of Boost.
2. Because str in Python 3 is unicode text, flex.std_string now returns unicode text in Python 3.  In Python 2, str is ascii text (byte string), so flex.std_string returns ascii text. This simplifies the migration because we do not need to put “b” or “u” in front of every string in our code. 
3. Pickling of flex objects requires byte strings to save and recover state.  To this end, we ensured that the getstate methods of flex objects return byte strings, as do flex.int.copy_to_byte_str() and flex.int_from_byte_str().
4. For cbflib, we had to convert to returning byte strings instead of unicode strings.  See 7bc6def31dc6952d01f3fe9916a5927ca8788a22.
5. Python3 syntax changes were made in the master branch for the following repos:  annlib_adaptbx, ccp4io_adaptbx.

We'd like to thank all the many contributors to this revision, including @nksauter, @bkpoon, @phyy-nx, @dermen, @graeme-winter, @Anthchirp, @ndevenish, @Oeffner.

### CODE REVIEW

**Comment by graeme-winter** [comment]
Thanks @nksauter @bkpoon @phyy-nx and others for this, will start to review today but as I am sure you can imagine will take a little while - I'd like to have the review complete ideally in about a week from this side. Please be aware that the chosen structure of 157 commits to achieve this rather than broad changes will increase the review overhead. 

I have added @ndevenish and @Anthchirp as reviewers on this side as they have considerable experience with Python 2 to 3 migration and will probably have much to offer. 

@bkpoon small detail - will you keep changes from mmtbx up-to-date with this branch so we can switch back and forth for testing?

Regarding review: I will be testing cctbx, dials, xia2 and other diamond tools across the usual platforms - I assume all PHENIX (and mmtbx) tests are handled in Berkeley.

**Comment by graeme-winter** [comment]
Reviewers: a detail - you will need to fetch the bootstrap from the py3 branch not master to reproduce the python3 conda environment - a detail which was missed in the instructions above. I happened to do that by accident and it worked  fine.

**Comment by ndevenish** [comment]
The usual way that I create new distributions should work in that case:
```sh
cd "<new location>"
git clone git@github.com:cctbx/cctbx_project.git modules/cctbx_project -b py3
ln -s modules/cctbx_project/libtbx/auto_build/bootstrap.py
```

**Comment by bkpoon** [comment]
@graeme-winter @ndevenish Thanks, I also normally set up a symbolic link so that bootstrap.py is always up to date. I have updated the instructions.

I have also updated the branch with the most recent commits to `master`.

**Comment by graeme-winter** [comment]
Following some discussion with the Berkeley group, my understanding is that the terms of reference for this pull request is "does this break your code running under Python 2.7" rather than "please review these changes" - with this in mind:

macOS High Sierra / dxtbx:
```
Results (79.55s):
     568 passed
       2 xfailed
      11 skipped
```

macOS High Sierra / dials:
```
Results (502.26s):
     758 passed
       3 xfailed
       3 skipped
```

The tests for dxtbx and dials are not broken on macOS High Sierra. RHEL6 tests need me to re-bootstrap for the new boost version needed by this version. I will take as a given that xia2 is not affected by these changes. 

I have also reproduced a subset of the results presented in the table above running with the Python 3.6  interpreter. Given the similarity of many of the changes to the changes in the closed PR #325 (and indeed, many of the commits making it across) I am confident within the terms of reference of this PR that the criteria are met.

**Comment by graeme-winter** [comment]
I do ask though that the changes are squashed and merged rather than merged with every one of the 159 commits separately.

**Comment by phyy-nx** [comment]
Squashed some of the commits.  Down to 109.

**Comment by bkpoon** [comment]
@graeme-winter This build should not need a different version of Boost. Are you getting an error when building with Boost 1.63?

**Comment by graeme-winter** [comment]
@bkpoon no, the issue was my base was old and I had boost 1.59

**Comment by ndevenish** [comment]
- Are there any regressions in python2 test suite running time?
- What are your plans for making sure people don't break python 3 syntax? I've seen people adding old-style exception syntax as recently as a few weeks ago.

I agree with Graeme in regards to more agressive squashing; some of the commits ([e.g.](https://github.com/cctbx/cctbx_project/commit/b401d1a0a857d3863add3d149156b388139e4e0e)) are outright reverted later; many of the commit messages are in many cases misleading or meaningless e.g. ["fix most cmp"](https://github.com/cctbx/cctbx_project/commit/0281ee762afa5ef253836c67a5a8bee9f8167e6e) changes many, many other things other than cmp. It would have been nice to have the commits clearly delineate between automatic transforms and manual changes.

We've been explicitly asked to avoid code quality comments so not listing any of the choices I found questionable, but I do lament that the chance hasn't been taken to update idioms e.g. in many cases rewriting `cmp` sorting to the more modern key-based would have been less work and much simpler code than the changes made here, `zip(range(len(x)), something)` touched for `list` removal to `enumerate`, things like that.

Outright problems in the pull:
- As I pointed out in the previous pull, parts of fable had been missed (which was handled here), and parts had missed out `__future__` imports. This has caused print statements in `tst_read.py` and `tst_equivalence.py` in fable to be double-converted, printing tuples instead of normal output.
- The line `import mmtbx.monomer_library.pdb_interpretation as pdb_inter` which was removed in https://github.com/cctbx/cctbx_project/commit/5568470add4cccaf7eff6367eb8b1924203d8d7d has been reintroduced into `cctbx/geometry_restraints/tst_nonbonded_overlaps.py`, probably inadvertantly in a rebase?

Compared to our syntax branch, I'm glad to report that it looks like the only differences are those listed in https://github.com/ndevenish/cctbx_project-fork/commit/7466c7053a610db2be07c77dbaf00d2dd8375b35 e.g. a handful of further changes and a few manual removals of redundant `list(range(` wrappers, taking the other 98.4% of our changes. I've rebased this onto our changes, which can be see at https://github.com/ndevenish/cctbx_project-fork/tree/py3_rebased_onto_python_3_syntax. I was careful to not make any further changes to our branch, except for an adapter patch https://github.com/ndevenish/cctbx_project-fork/commit/2935cea40f713232b504657df7251f4fdee1d330 that reshuffled the import positions so that they were in the same positions as in the original py3 branch.

**Comment by ndevenish** [comment]
I've just rewritten the authorship in some of our commits

**Comment by dermen** [comment]
I think its important to clarify for the groups sake that the majority of this pull request (maybe 95% of the work) was as listed in the title (cross compatibility), as opposed to the syntax portion (which we used [python-modernize](https://python-modernize.readthedocs.io/en/latest/) as per this[ neat article](https://medium.com/@boxed/moving-a-large-and-old-codebase-to-python3-33a5a13f8c99)).  Getting python3 to not complain about syntax when interpereting a script is one small part of this pull request, however getting the 400+ tests to run under python3 with boost wrappers which were written with python2 was the majority of the effort behind this pull request.

**Comment by graeme-winter** [comment]
I and others have already recognised [1] the efforts which have gone into this - we know from experience that this is not trivial and requires many manual steps. Also the previous work in now closed #325 _explicitly stated_ that "we believe these changes move us towards P3 syntax compatibility - not true compatibility as we've not addressed e.g. bytes / strings / unicode here, but should help." It is also worth stating that this work had been recognised as needed in #80 a long time ago, but until we started work no progress had been made for 18 months. 

The review for that pull request included a number of criticisms we attempted to address as well as a few which were not well founded, before the requirement that the changes be reviewed _line by line_ [2] followed shortly by closing without further comment. 

We who are _not_ in "the group" recognise the work needed to get e.g. Boost working from the work @Anthchirp did on unmerged (though picked from) PR #198 almost exactly a year ago. 

@ndevenish also raises some valid questions which I think deserve attention:

1. Are there any regressions in python2 test suite running time?
2. What are your plans for making sure people don't break python 3 syntax? I've seen people adding old-style exception syntax as recently as a few weeks ago.

The former was an explicit criticism of the previous work, and so should be commented on here. On the latter we have experience of maintaining xia2, dials, dxtbx, fast_dp and other packages across multiple versions. The questions have merit. 

Re: "Getting python3 to not complain about syntax when interpreting a script is one small part of this pull request" - this would have been much easier to see if the work had been staged e.g. perform the syntax transformation first, then a much smaller change set to make the actual meaningful code changes - here they are interleaved as a design decision. @ndevenish points out that the vast majority of changes (>> 90%) are common which is _good_ and _informative_ since it massively reduces the workload of reviewers who understand the automated transformations. 

That said we were asked not to review the code changes in this pull request and I have endeavoured to follow this guidance, limiting my comments only to whether or not the tests now fail. I am however responsible for the reliable running of software on Diamond beamlines and responsible to xia2 and dials users for the long game, so even though I have no say in these changes I am responsible for supporting them, warts and all. 

I would like to take the opportunity to highlight the developer guidance on the wiki, and question whether this is working well in practice. 

[1] https://github.com/cctbx/cctbx_project/pull/339#issuecomment-495072726 
[2] https://github.com/cctbx/cctbx_project/pull/325#issuecomment-490504957

**Comment by phyy-nx** [comment]
Right, most of the effort here is on functionality.  See for example commits like 7a3673ce4453155445fe0f227fbca5f18d14986c and 5840844dc53fed64f65ab42ac948180c36b1d253 which were fixing seg faults.

Regarding your other points,
- We ran nightly time tests on scitbx, cctbx and smtbx. Their performances weren't affected as of when the pull request was made.  We can run them again.
- We have a continuous integration buildbot server checking python3 syntax and running the tests in python 3.  We'll enable email notification for py3 syntax and tests for this buildbot server when we merge this branch.
- Sorry, we won't be squashing the commits further.  We value the commit history and the commit messages.  I recognize the flood of emails will be annoying.  Sorry about that.
- Idioms and modernization is orthogonal to this work.  This was specifically to get things running in python 3.
- Re: fable and the extra import, we will look at these.  Thanks!!

**Comment by graeme-winter** [comment]
> Right, most of the effort here is on functionality. See for example commits like [7a3673c](https://github.com/cctbx/cctbx_project/commit/7a3673ce4453155445fe0f227fbca5f18d14986c) and [5840844](https://github.com/cctbx/cctbx_project/commit/5840844dc53fed64f65ab42ac948180c36b1d253) which were fixing seg faults.
> 

_right_ this is almost certainly true and _completely invisible_ because buried in hundreds of other commits. We knew for a long time that this would be a lot of work, and the syntax transformation is the easy stage 1 - hence proposing we do that _first_ then get stuck into the hard stuff. It's a shame that this approach was rejected. 

I for one do not feel comfortable working on a collaborative project where one may not ask questions which are asked of you. Being asked to review pull requests without reviewing the code changes is bad enough.

**Comment by bkpoon** [comment]
@graeme-winter 
> It is also worth stating that this work had been recognised as needed in #80 a long time ago, but until we started work no progress had been made for 18 months.

I'm not sure where this is coming from. The `libtbx` directory was changed to be able to configure and build CCTBX programs in Python 3 in November 2018. The last commit for that was a8c1a4e60409776b551af7fcf0731cb62317c393. Other commits for that work have commit messages prefixed with "libtbx: Python 2/3". @nksauter also made changes to `fable` here 61c6565f324579f76966f88e8a3b9083da7caa7d. There was also a pull request (#245) for certain changes in `libtbx`.

Then I worked on `conda` so that we have consistent testing environments on all 3 platforms, linux, macOS, and Windows, which is needed to test functionality in Python 3.

**Comment by dermen** [comment]
Well moving forward, I hope this can at least help dig out commits that are non py-syntax. Here are the .cpp and .h files that diff between master and py3:

# .cpp
```
diff --git a/cbflib_adaptbx/detectors/boost_python/cbflib_ext.cpp b/cbflib_adaptbx/detectors/boost_python/cbflib_ext.cpp
diff --git a/cctbx/crystal/close_packing_bpl.cpp b/cctbx/crystal/close_packing_bpl.cpp
diff --git a/cctbx/eltbx/boost_python/chemical_elements_ext.cpp b/cctbx/eltbx/boost_python/chemical_elements_ext.cpp
diff --git a/cctbx/eltbx/boost_python/xray_scattering_ext.cpp b/cctbx/eltbx/boost_python/xray_scattering_ext.cpp
diff --git a/cctbx/maptbx/boost_python/pymol_interface.cpp b/cctbx/maptbx/boost_python/pymol_interface.cpp
diff --git a/cctbx/miller/boost_python/index_generator.cpp b/cctbx/miller/boost_python/index_generator.cpp
diff --git a/iotbx/pdb/hierarchy_ext.cpp b/iotbx/pdb/hierarchy_ext.cpp
diff --git a/iotbx/pdb/input_bpl.cpp b/iotbx/pdb/input_bpl.cpp
diff --git a/iotbx/pdb/xray_structure_bpl.cpp b/iotbx/pdb/xray_structure_bpl.cpp
diff --git a/scitbx/array_family/boost_python/flex_int.cpp b/scitbx/array_family/boost_python/flex_int.cpp
diff --git a/scitbx/array_family/boost_python/flex_std_string.cpp b/scitbx/array_family/boost_python/flex_std_string.cpp
diff --git a/scitbx/array_family/boost_python/loops.cpp b/scitbx/array_family/boost_python/loops.cpp
diff --git a/scitbx/array_family/boost_python/numpy_bridge.cpp b/scitbx/array_family/boost_python/numpy_bridge.cpp
diff --git a/scitbx/math/boost_python/golay.cpp b/scitbx/math/boost_python/golay.cpp
diff --git a/scitbx/math/boost_python/halton.cpp b/scitbx/math/boost_python/halton.cpp
diff --git a/scitbx/math/boost_python/unimodular_generator.cpp b/scitbx/math/boost_python/unimodular_generator.cpp
diff --git a/scitbx/sparse/boost_python/vector.cpp b/scitbx/sparse/boost_python/vector.cpp
``` 

# .h
```
diff --git a/boost_adaptbx/iterator_range.h b/boost_adaptbx/iterator_range.h
diff --git a/cctbx/adptbx.h b/cctbx/adptbx.h
diff --git a/iotbx/pdb/hierarchy_bpl.h b/iotbx/pdb/hierarchy_bpl.h
diff --git a/iotbx/pdb/write_utils_bpl.h b/iotbx/pdb/write_utils_bpl.h
diff --git a/scitbx/array_family/boost_python/byte_str.h b/scitbx/array_family/boost_python/byte_str.h
diff --git a/scitbx/array_family/boost_python/flex_pickle_double_buffered.h b/scitbx/array_family/boost_python/flex_pickle_double_buffered.h
diff --git a/scitbx/boost_python/iterator_wrappers.h b/scitbx/boost_python/iterator_wrappers.h
diff --git a/scitbx/random/boost_python/random.h b/scitbx/random/boost_python/random.h
```

You can see the git logs like this running the command from the repository root

```
find -name '*.cpp' -print0 | xargs -0 git diff master py3
```

**Comment by graeme-winter** [comment]
> @graeme-winter
> 
> > It is also worth stating that this work had been recognised as needed in #80 a long time ago, but until we started work no progress had been made for 18 months.
> 
> I'm not sure where this is coming from. The `libtbx` directory was changed to be able to configure and build CCTBX programs in Python 3 in November 2018. The last commit for that was [a8c1a4e](https://github.com/cctbx/cctbx_project/commit/a8c1a4e60409776b551af7fcf0731cb62317c393). Other commits for that work have commit messages prefixed with "libtbx: Python 2/3". @nksauter also made changes to `fable` here [61c6565](https://github.com/cctbx/cctbx_project/commit/61c6565f324579f76966f88e8a3b9083da7caa7d). There was also a pull request (#245) for certain changes in `libtbx`.
> 
> Then I worked on `conda` so that we have consistent testing environments on all 3 platforms, linux, macOS, and Windows, which is needed to test functionality in Python 3.

@bkpoon I understand these things - however, the work to move forward was a very long time coming, and in turn held up work in being able to port dials (which is in turn holding up other work on the shop floor)

We are now in a position to get this work going, which is a good thing, and - as I have _repeatedly_ stated we recognise that the syntax phase of the work was the easiest. The closed PR #325 however was triggered by repeated radio silence or the odd "2to3" type commit which would be the response to asking how this was going on mailing lists and conference calls, and the lack of progress visible on https://github.com/cctbx/cctbx_project/projects/2. The disconnect between https://github.com/cctbx/cctbx_project/wiki/Python-3-roadmap and real-life was also an issue.

I suspect merging this PR with prejudice is the way forward, since the rest of the work can then get moving. We still have dials, dxtbx and xia2 to do which will also be complicated...

**Comment by graeme-winter** [comment]
> I hope this can at least help dig out commits that are non py-syntax. Here are the .cpp and .h files that diff between master and py3:

Again, know there is some nasties in here - would have been great to have them clearer rather than needing to be dug out. I remember @Anthchirp going through some tricky coding to make the boost changes work out so I suspect this deserves review more than many of the other commits.

**Comment by Anthchirp** [comment]
@ndevenish 's mail address in the last commit is misspelt ([also there is no need to mention the commit author as co-authored-by](https://help.github.com/en/articles/creating-a-commit-with-multiple-authors))

**Comment by Anthchirp** [comment]
@bkpoon Did you check your changes in 5502cae actually work? As I have noted just about a year ago in https://github.com/cctbx/cctbx_project/commit/aeec03e7664d136f278f2e625d76ad80075314d2 and https://github.com/cctbx/cctbx_project/pull/202 and https://github.com/cctbx/cctbx_project/pull/184#issuecomment-394183432 boost numpy does not work on Windows with 1.63, which was how that `if` statement you just changed came into being. This was also the reason why I have been trying to get us to move to 1.64 for the last year up until 20 days ago (https://github.com/cctbx/cctbx_project/pull/184#issuecomment-491262051) with pull request https://github.com/dials/boost/pull/1

**Comment by bkpoon** [comment]
@Anthchirp Building with the Boost Numpy interface on Windows is working on our build machines after my commit. The change basically builds `boost_numpy.lib`, which allows for linking. Are you getting build errors?

However, the change causes `boost_numpy.dll` to not be built. I'm looking for a better way than adding a Boost version check so that Boost 1.63 has the .lib file and newer versions of Boost build the DLL, but it's looking like it might be necessary.

**Comment by nksauter** [comment]
All concerned, 
At this point all the Reviewers have approved the pull request (@luc-j-bourhis and @pcxod by separate email to me).  Therefore our plan is as follows:
On Tuesday June 3 we will rebase this branch against the master and resolve all conflicts; then merge into the master at 12:00 noon Pacific time (GMT -7).
Thanks to all who contributed to the pull request.-- @nksauter

**Pull request merged**
