### PR TITLE
Don't divide by zero if rotating by 0°

### PR DESCRIPTION
**Pull request by benjaminhwilliams**
The quaternion of a 0° rotation is, straightforwardly, 1.  Sometimes, since the axis direction for a 0° rotation is arbitrary, `axis_and_angle_as_unit_quaternion` may be called with an angle of 0 and a placeholder axis of (0, 0, 0).  In this case, return early to guard against a `ZeroDivisionError` when trying to normalise the axis.

### CODE REVIEW

**Comment by benjaminhwilliams** [comment]
The test failure seems to be in `tst_bcr.py`, which seems unrelated to this PR and I notice that @bkpoon has since marked it as unstable on master, so I've merged master into this branch and hopefully the CI will now pass.

**Comment by benjaminhwilliams** [comment]
I've also added a test that highlights how I discovered this problem.  I found some old code in DIALS that was effectively trying to do a round trip from rotation matrix to quaternion, to axis and angle, to quaternion, to rotation matrix.  When you try this, using the ℝ³ identity matrix as your starting point and without the changes in this PR, you get
```python
>>> from scitbx import matrix
>>> id = matrix.identity(3)
>>> q = id.r3_rotation_matrix_as_unit_quaternion()
>>> angle, axis = q.unit_quaternion_as_axis_and_angle()
>>> axis.axis_and_angle_as_r3_rotation_matrix(angle)
Traceback (most recent call last):
  File "/home/ekm22040/DIALS/conda_base/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-7cb59b38bfe8>", line 1, in <module>
    axis.axis_and_angle_as_r3_rotation_matrix(angle)
  File "/home/ekm22040/DIALS/modules/cctbx_project/scitbx/matrix/__init__.py", line 461, in axis_and_angle_as_r3_rotation_matrix
    uq = self.axis_and_angle_as_unit_quaternion(angle=angle, deg=deg)
  File "/home/ekm22040/DIALS/modules/cctbx_project/scitbx/matrix/__init__.py", line 457, in axis_and_angle_as_unit_quaternion
    u,v,w = self.normalize().elems
  File "/home/ekm22040/DIALS/modules/cctbx_project/scitbx/matrix/__init__.py", line 266, in normalize
    return self / abs(self)
  File "/home/ekm22040/DIALS/modules/cctbx_project/scitbx/matrix/__init__.py", line 154, in __truediv__
    return rec([e/other for e in self.elems], self.n)
  File "/home/ekm22040/DIALS/modules/cctbx_project/scitbx/matrix/__init__.py", line 154, in <listcomp>
    return rec([e/other for e in self.elems], self.n)
ZeroDivisionError: float division by zero
```

**Comment by benjaminhwilliams** [comment]
I see there are now a couple of different failing tests, `scitbx.linalg.tests.tst_svd.exercise_inverse` and fails in one pipeline and `cma_es.tst_cma_es.test_cma_es_file` fails in another.  There doesn't seem to be any consistency in the failures between different pipelines.  I can't see how these failures are related to this PR and I can't reproduce them locally.  I don't really have much experience of the CCTBX CI set-up.  Are these just idiosyncrasies that can be ignored?

**Comment by bkpoon** [comment]
Yep, those failures can be ignored. They fail less than 1% of the time, so I wouldn't consider them unstable. I will also generally re-run the failed jobs once the pipeline completes so that they are cleared.

Also, generally, you can ignore the results from the "CI branch" and "XFEL CI branch" pipelines since they run on the current state of your branch. The "Full" and "XFEL CI" pipelines are the ones that run on the merged code.

**Comment by benjaminhwilliams** [comment]
It looks like I've got all the CI checks to pass now.  I'm not sure who's best placed to review this.  @bkpoon, any suggestions?

**Comment by bkpoon** [comment]
I chatted with @nksauter and I can merge this.

**Comment by benjaminhwilliams** [comment]
Thanks.

**Pull request merged**
