### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by clacri**
Just added a link to the CONTRIBUTING.md in the main landing page (the README).

### CODE REVIEW

**Review by bkpoon — COMMENTED** [review]
Maybe this should be higher up? Like between "Building a development version" and "Nightly builds"?

**Comment by Oeffner** [comment]
Agreed. I would place it just after the "Building a development version" section.

**Review by Oeffner — APPROVED** [review]

**Comment by clacri** [comment]
Ok, will change it

**Review by bkpoon — APPROVED** [review]

**Comment by clacri** [comment]
Thank you!!!

**Pull request merged**
