### PR TITLE
wxPython4 fixes for multiplicity viewer

### PR DESCRIPTION
**Pull request by rjgildea**
* wx.TaskBarIcon -> wx.adv.TaskBarIcon
* wx.EmptyIcon -> wx.Icon
* wx.EmptyBitmap -> wx.Bitmap
* wx.PyPanel -> wx.Panel
* wx.PyValidator -> wx.Validator
* AddLabelTool -> AddTool
* AppendItem -> Append
* wx.OPEN -> wx.FD_OPEN
* wx.SAVE -> wx.FD_SAVE

### CODE REVIEW

**Comment by rjgildea** [comment]
I still get the following error when trying to save an image from the 3D view - I assume this is a Python3/unicode issue, but I'm not sure what the solution is:
```
$ cctbx.multiplicity_viewer $(dials.data get -q x4wide_processed)/AUTOMATIC_DEFAULT_scaled_unmerged.mtz 
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 975: invalid start byte
Traceback (most recent call last):
  File "/Users/rjgildea/software/cctbx/modules/cctbx_project/crys3d/hklview/frames.py", line 737, in OnSave
    extensions=["png"])
  File "/Users/rjgildea/software/cctbx/modules/cctbx_project/gltbx/wx_viewer.py", line 734, in save_screen_shot
    file_name=file_name, extensions=extensions_pil)
  File "/Users/rjgildea/software/cctbx/modules/cctbx_project/gltbx/wx_viewer.py", line 671, in save_screen_shot_via_pil
    x=0, y=0, width=self.w, height=self.h)
  File "/Users/rjgildea/software/cctbx/modules/cctbx_project/gltbx/viewer_utils.py", line 27, in read_pixels_to_pil_image
    data = read_pixels_to_str(x=x, y=y, width=width, height=height)
  File "/Users/rjgildea/software/cctbx/modules/cctbx_project/gltbx/viewer_utils.py", line 17, in read_pixels_to_str
    pixels=pixels)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 975: invalid start byte
```

**Comment by Anthchirp** [comment]
This error occurs in the C++ code where the image information is read out and we then try to coerce it into a Python string (rather than the correct byte array)

Relevant pointers are
https://github.com/cctbx/cctbx_project/blob/545cae8c9f9eb8e36f659dbec07a37ae55658b1c/gltbx/generate_functions_bpl.py#L380-L392
and
https://github.com/cctbx/cctbx_project/blob/545cae8c9f9eb8e36f659dbec07a37ae55658b1c/gltbx/pointer_args_bpl.h#L140

The relevant C++ function `glReadPixels` is defined/generated in `build/gltbx/gl_functions_10_bpl.cpp`

**Comment by rjgildea** [comment]
Thanks @bkpoon, save image now works for me. However I do get a bunch of compiler deprecation warnings on mac - I don't know if this is anything to be concerned about. Otherwise happy to merge as is.

```
In file included from gltbx/glu_functions_01_bpl.cpp:9:
In file included from /Users/rjgildea/software/cctbx/modules/cctbx_project/gltbx/special_wrapper_support.h:7:
/Users/rjgildea/software/cctbx/modules/cctbx_project/gltbx/error.h:17:24: warning: 'gluErrorString' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated.
      (Define GL_SILENCE_DEPRECATION to silence these warnings) [-Wdeprecated-declarations]
    const GLubyte* p = gluErrorString(code);
...
gltbx/glu_functions_00_bpl.cpp:33:5: warning: 'gluBeginCurve' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings)
      [-Wdeprecated-declarations]
    gluBeginCurve(nurb);
    ^
/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:240:13: note: 'gluBeginCurve' has been explicitly marked deprecated here
extern void gluBeginCurve (GLUnurbs* nurb) OPENGL_DEPRECATED(10.0, 10.9);
            ^
gltbx/glu_functions_00_bpl.cpp:44:5: warning: 'gluEndCurve' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings)
      [-Wdeprecated-declarations]
    gluEndCurve(nurb);
    ^
/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:256:13: note: 'gluEndCurve' has been explicitly marked deprecated here
extern void gluEndCurve (GLUnurbs* nurb) OPENGL_DEPRECATED(10.0, 10.9);
            ^
gltbx/glu_functions_00_bpl.cpp:55:5: warning: 'gluBeginPolygon' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings)
      [-Wdeprecated-declarations]
    gluBeginPolygon(tess);
    ^
/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:241:13: note: 'gluBeginPolygon' has been explicitly marked deprecated here
extern void gluBeginPolygon (GLUtesselator* tess) OPENGL_DEPRECATED(10.0, 10.9);
            ^
gltbx/glu_functions_00_bpl.cpp:66:5: warning: 'gluEndPolygon' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings)
      [-Wdeprecated-declarations]
    gluEndPolygon(tess);
    ^
/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:257:13: note: 'gluEndPolygon' has been explicitly marked deprecated here
extern void gluEndPolygon (GLUtesselator* tess) OPENGL_DEPRECATED(10.0, 10.9);
            ^
gltbx/glu_functions_00_bpl.cpp:77:5: warning: 'gluBeginSurface' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings)
      [-Wdeprecated-declarations]
    gluBeginSurface(nurb);
    ^
/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:242:13: note: 'gluBeginSurface' has been explicitly marked deprecated here
extern void gluBeginSurface (GLUnurbs* nurb) OPENGL_DEPRECATED(10.0, 10.9);
            ^
gltbx/glu_functions_00_bpl.cpp:88:5: warning: 'gluEndSurface' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings)
      [-Wdeprecated-declarations]
    gluEndSurface(nurb);
    ^
/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:258:13: note: 'gluEndSurface' has been explicitly marked deprecated here
extern void gluEndSurface (GLUnurbs* nurb) OPENGL_DEPRECATED(10.0, 10.9);
            ^
gltbx/glu_functions_00_bpl.cpp:99:5: warning: 'gluBeginTrim' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings)
      [-Wdeprecated-declarations]
    gluBeginTrim(nurb);
    ^
/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:243:13: note: 'gluBeginTrim' has been explicitly marked deprecated here
extern void gluBeginTrim (GLUnurbs* nurb) OPENGL_DEPRECATED(10.0, 10.9);
            ^
gltbx/glu_functions_00_bpl.cpp:110:5: warning: 'gluEndTrim' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings)
      [-Wdeprecated-declarations]
    gluEndTrim(nurb);
    ^
/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:259:13: note: 'gluEndTrim' has been explicitly marked deprecated here
extern void gluEndTrim (GLUnurbs* nurb) OPENGL_DEPRECATED(10.0, 10.9);
            ^
gltbx/glu_functions_00_bpl.cpp:193:5: warning: 'gluCylinder' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings)
      [-Wdeprecated-declarations]
    gluCylinder(quad, base, top, height, slices, stacks);
    ^
/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:251:13: note: 'gluCylinder' has been explicitly marked deprecated here
extern void gluCylinder (GLUquadric* quad, GLdouble base, GLdouble top, GLdouble height, GLint slices, GLint stacks) OPENGL_DEPRECATED(10.0, 10.9);
            ^
gltbx/glu_functions_00_bpl.cpp:204:5: warning: 'gluDeleteNurbsRenderer' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated.
      (Define GL_SILENCE_DEPRECATION to silence these warnings) [-Wdeprecated-declarations]
    gluDeleteNurbsRenderer(nurb);
    ^
/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:252:13: note: 'gluDeleteNurbsRenderer' has been explicitly marked deprecated here
extern void gluDeleteNurbsRenderer (GLUnurbs* nurb) OPENGL_DEPRECATED(10.0, 10.9);
            ^
gltbx/glu_functions_00_bpl.cpp:215:5: warning: 'gluDeleteQuadric' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings)
      [-Wdeprecated-declarations]
    gluDeleteQuadric(quad);
    ^
/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:253:13: note: 'gluDeleteQuadric' has been explicitly marked deprecated here
extern void gluDeleteQuadric (GLUquadric* quad) OPENGL_DEPRECATED(10.0, 10.9);
            ^
gltbx/glu_functions_01_bpl.cpp:33:5: warning: 'gluDeleteTess' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings)
      [-Wdeprecated-declarations]
    gluDeleteTess(tess);
    ^
/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:254:13: note: 'gluDeleteTess' has been explicitly marked deprecated here
extern void gluDeleteTess (GLUtesselator* tess) OPENGL_DEPRECATED(10.0, 10.9);
            ^
gltbx/glu_functions_01_bpl.cpp:56:5: warning: 'gluDisk' is deprecated: first deprecated in macOS 10.9 - OpenGL API deprecated. (Define GL_SILENCE_DEPRECATION to silence these warnings)
      [-Wdeprecated-declarations]
    gluDisk(quad, inner, outer, slices, loops);
    ^
/System/Library/Frameworks/OpenGL.framework/Headers/glu.h:255:13: note: 'gluDisk' has been explicitly marked deprecated here
extern void gluDisk (GLUquadric* quad, GLdouble inner, GLdouble outer, GLint slices, GLint loops) OPENGL_DEPRECATED(10.0, 10.9);
            ^
...
```

**Comment by bkpoon** [comment]
Great! The fix is tentative in the sense that if other issues come up, a better solution for handling text versus byte strings will be needed.

For the deprecation warnings, I think they can be ignored if it's on macOS since it is deprecating OpenGL in general.

Feel free to merge when you're ready.

**Pull request merged**
