### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by bkpoon**

### CODE REVIEW

**Comment by Anthchirp** [comment]
want me to
* add changes from #294 to this pull request?
* convert send2trash to using the pypi package?

**Comment by bkpoon** [comment]
Sounds good!

**Comment by bkpoon** [comment]
I rolled back cython to 0.28.6 and updated openssl to 1.0.2r since that was available.

**Comment by bkpoon** [comment]
Sorry! I didn't know this was waiting for me.

**Comment by Anthchirp** [comment]
no worries, all good :)
Thanks

**Pull request merged**
