### PR TITLE
Remove exp_id from cctbx.xfel.merge

### PR DESCRIPTION
**Pull request by phyy-nx**
Closes dials/dials#1858.

Background: exp_id is a column of experiment identifiers, originally developed in parallel with the experiment_identifier map in DIALS.  Now that the experiment_identifier map is standard in DIALS, exp_id is redundant, so this PR removes it.

Note this PR makes heavy use of two convenience methods in DIALS:

- [concat](https://github.com/dials/dials/blob/main/src/dials/array_family/flex_ext.py#L511-L527): takes two or more reflection tables and concatenates them together, renumbering the `'id'` column and taking care of the experiment_identifer map
- [reset_ids](https://github.com/dials/dials/blob/main/src/dials/array_family/flex_ext.py#L1224-L1236): resets the `'id'` column, accounting for any gaps. Useful after using `select` to remove reflections from a table.

### CODE REVIEW

**Review by nksauter — CHANGES_REQUESTED** [review]
I've read through the pull request and I agree that the retirement of "exp_id" is sensible.  I'm not in a position to test the code per se within cctbx_project.  Instead I would ask if you could create a separate pull request within the psii_spread repository, where we are using "exp_id" for active data processing.  I could then simultaneously test the two PRs together.  I do have a concern:  will this PR force is to completely reprocess our data from the start, or can we operate on existing expt/refl pairs?  If reprocess, it would be a major headache; if existing pairs, it would be a great outcome.

**Comment by phyy-nx** [comment]
The merging tests in xfel_regression are all passing.  I've started on psii_spread, and am about halfway through it.  I'll ping you when that's ready.

I tested on old dataset (scaling/postrefinement results) and it worked fine without needing explicit backwards compatibility besides what's already there (removing the exp_id column in memory during file reading).  If something comes up during testing, I can add add any needed backwards compatibility.

**Review by dermen — CHANGES_REQUESTED** [review]
I will attempt to make an official test, but for now, I believe this patch is all thats needed from my end: 

```diff
diff --git a/xfel/merging/application/input/file_loader.py b/xfel/merging/application/input/file_loader.py
index 3b8afce651..71c6c43bc3 100644
--- a/xfel/merging/application/input/file_loader.py
+++ b/xfel/merging/application/input/file_loader.py
@@ -145,7 +145,7 @@ class simple_file_loader(worker):
           # NOTE: these are un-prunable
           reflections["input_refl_index"] = flex.int(
             list(range(len(reflections))))
-          reflections["orig_exp_id"] = reflections['id']
+          reflections["original_id"] = reflections['id']
           assert file_names_mapping is not None
           exp_ref_pair = os.path.abspath(experiments_filename), os.path.abspath(reflections_filename)
           this_refl_fileMappings = [file_names_mapping[exp_ref_pair]]*len(reflections)
diff --git a/xfel/merging/command_line/merge.py b/xfel/merging/command_line/merge.py
index d1539276e3..c9abead826 100644
--- a/xfel/merging/command_line/merge.py
+++ b/xfel/merging/command_line/merge.py
@@ -212,7 +212,7 @@ class Script(object):
     if self.params.output.expanded_bookkeeping:
       if self.params.input.persistent_refl_cols is None:
         self.params.input.persistent_refl_cols = []
-      keysCreatedByMerge = ["file_list_mapping", "is_odd_experiment"]
+      keysCreatedByMerge = ["input_refl_index", "original_id", "file_list_mapping", "is_odd_experiment"]
       for key in keysCreatedByMerge:
         if key not in self.params.input.persistent_refl_cols:
           self.params.input.persistent_refl_cols.append(key)

```

Happy to discuss

**Comment by phyy-nx** [comment]
@dermen done, thanks.  I also changed the comment for `expanded_bookkeeping` to "1- modified experiment identifier that contains the image number and lattice number".  Let me know if that's right?

**Review by nksauter — APPROVED** [review]
All development tests on psii_spread now work, so I am approving the pull request.  I only ask that the merge to master be done to coincide with the associated merges on dials and psii_spread.

**Comment by phyy-nx** [comment]
Righto.  I've prepped dials/dials#2281 to handle empty tables and reverted the now unnecessary checks here and in psii_spread.  When that goes through I'll merge this, xfel_regression, and psii_spread at the same time.

**Review by dermen — APPROVED** [review]
nice!

**Pull request merged**
