### PR TITLE
Fix some corner cases in the 'counting_sorted' binning algorithm

### PR DESCRIPTION
**Pull request by benjaminhwilliams**
Working with small molecule diffraction data, with few reflections, has highlighted an issue with the `'counting_sorted'` binning algorithm of `cctbx.miller.set` with implications for `iotbx.merging_statistics.dataset_statistics`, amongst other things.

The problem occurs in cases where there are few reflections overall, and relatively many symmetrically-nonequivalent reflections with coincidentally close _d_-spacings, as is not uncommon in small molecule work.  The current algorithm can result in the creation of empty, zero-width bins.  This PR introduces the following slight modifications to the existing behaviour:
- In `cctbx.miller.set.setup_binner_counting_sorted`, bin edges are determined based on the set of _d_-values unique to within a tolerance specified with the existing parameter `d_tolerance`, rather than all the _d_-values, thereby avoiding empty bins.
- The way `cctbx.miller.set.setup_binner_counting_sorted` treats the parameters `reflections_per_bin` and `n_bins` is changed slightly so that if both are not `None`, then `reflections_per_bin` is treated as minimum number of reflections per bin, and `n_bins` is treated as the maximum number of reflections per bin.  Previously if `n_bins` and `reflections_per_bin` were both provided, then only `n_bins` was used and `reflections_per_bin` was ignored.
- A new optional parameter `reflections_per_bin` in `iotbx.merging_statistics` exposes the corresponding parameter in `cctbx.miller.set.setup_binner_counting_sorted`.  It is ignored for other binning algorithms, where it has no meaning.

New and updated tests for this behaviour are included.

With corresponding modifications in DIALS, this is a partial fix for https://github.com/dials/dials/issues/1097.

### CODE REVIEW

**Comment by benjaminhwilliams** [comment]
I'm trying to find out if this PR can be responsible for any of the unsuccessful CI checks but it's not easy to decipher the tangle of failures.  I can't see any of these failing tests that can possibly have been affected by the changes introduced here.  Quite a lot of them are simply `ImportError: No module named scipy`.  @bkpoon, is this normal for the CCTBX CI checks?  I'll merge master into this branch to see if that makes any difference.

**Comment by Anthchirp** [comment]
these are due to https://github.com/cctbx/cctbx_project/issues/434

**Comment by benjaminhwilliams** [comment]
OK, I guess that accounts for the missing SciPy imports, but perhaps not the other failing tests here, such as `cctbx_project/smtbx/refinement/tests/tst_least_squares.py` failing with an incorrect expectation value on Ubuntu 14.04.  Hopefully @bkpoon can provide some guidance as to how many red crosses is too many red crosses for a PR to be merged.

**Comment by bkpoon** [comment]
The Base builds will fail because of the missing `scipy` imports and there are some unstable tests (like the one in `smtbx`). Nothing new seems to be failing.

**Comment by benjaminhwilliams** [comment]
Great, thanks @bkpoon, that's good to know.

@rjgildea, could you suggest a suitable reviewer?  I don't know who's best placed.

**Pull request merged**
