### PR TITLE
Putative fix for multiplicity viewer in py3 (#430)

### PR DESCRIPTION
**Pull request by graeme-winter**

### CODE REVIEW

**Comment by dagewa** [comment]
This does indeed fix the multiplicity viewer for me on Python 3. Is it ready for review?

**Comment by dagewa** [comment]
At least, it allows the viewer to start. The "Save image" functionality is broken
```
AttributeError: module 'wx' has no attribute 'SAVE'
```

**Comment by dagewa** [comment]
Just remembered I noted this already in #430

**Comment by Anthchirp** [comment]
Suspect this has been superseded by https://github.com/cctbx/cctbx_project/pull/474
Please reopen if this is not the case

**Pull request closed without merging**
