### PR TITLE
Streamline the two exascale simulation kernels.

### PR DESCRIPTION
**Pull request by nksauter**
Debranch kernel now a) uses vec3 rather than Holton-vec4; b) marshals all mos-tics and phi-tics into one list of crystal orientations; c) aligns exact order of operations (*,/) with kokkosSpotsKernel.

### CODE REVIEW

**Comment by nksauter** [comment]
debranch_maskall_kernel is now about 45% faster than before on the cry11ba simulation test.  Simulated images are identical (before vs after) when doing a spot check to integer precision on each pixel.

**Comment by mewall** [comment]
Does the diffuse simulation need to be checked or can we safely assume it will be the same?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: nksauter ***@***.***>
Sent: Thursday, January 11, 2024 4:19:17 PM
To: cctbx/cctbx_project ***@***.***>
Cc: Wall, Michael E ***@***.***>; Review requested ***@***.***>
Subject: [EXTERNAL] Re: [cctbx/cctbx_project] Streamline the two exascale simulation kernels. (PR #954)


@nksauter<https://urldefense.com/v3/__https://github.com/nksauter__;!!Bt8fGhp8LhKGRg!C40sgSpkkK1ddG182hnELPxXJOEYg3lz6rHSuS241wEnP5tizyLRKZxDJbFFs28YcdPkqYjaGJ92yA9B9bYYdFw9$> requested your review on: #954<https://urldefense.com/v3/__https://github.com/cctbx/cctbx_project/pull/954__;!!Bt8fGhp8LhKGRg!C40sgSpkkK1ddG182hnELPxXJOEYg3lz6rHSuS241wEnP5tizyLRKZxDJbFFs28YcdPkqYjaGJ92yA9B9Smo9Gqr$> Streamline the two exascale simulation kernels..

**Comment by nksauter** [comment]
Mike,
I've assigned you as a reviewer to get your detail-oriented review.  PR#954 makes extensive and intrusive changes to the debranch_maskall kernel.  There may be code conflicts with nanobragg_diffuse_aaron2 and breaking changes.  I'd recommend creating a new git clone, rebasing the diffuse against exafel_kernels2 and rerunning whatever test you have to assure correct function.  Once you are OK, I'll merge PR#954 and then get to work on the diffuse PR.  I want to change your code so there are two options, +/- diffuse, where the minus option has no code involvement with diffuse. I believe this is a job for C++ policies and it will be the first instance using them in simtbx.

**Comment by nksauter** [comment]
I'm going to make a few cosmetic changes then merge.  Last chance to comment.  These code changes should give a big improvement in the simulation step of the KPP pipeline.

**Pull request merged**
