### PR TITLE
Gpu to master less

### PR DESCRIPTION
**Pull request by dermen**
Request permission to merge nanoBragg cuda code written by @jmholton  and Giles Mullen into master. In addition to adding the cuda code, this allows compilation for multiple architectures and a way to set device Id at runtime from a nanoBragg instance (for working on multi-GPU nodes). Does the cuda code need a copyright ?

### CODE REVIEW

**Comment by dagewa** [comment]
On this branch the build fails with
```
ImportError: No module named util:
  File "/home/david/sw/cctbx/build/SConstruct", line 6:
    SConscript("libtbx/SConscript")
  File "/home/david/sw/cctbx/modules/scons/engine/SCons/Script/SConscript.py", line 607:
    return method(*args, **kw)
  File "/home/david/sw/cctbx/modules/scons/engine/SCons/Script/SConscript.py", line 544:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/home/david/sw/cctbx/modules/scons/engine/SCons/Script/SConscript.py", line 253:
    call_stack[-1].globals)
  File "/home/david/sw/cctbx/modules/cctbx_project/libtbx/SConscript", line 1333:
    enable_cuda_if_possible()
  File "/home/david/sw/cctbx/modules/cctbx_project/libtbx/SConscript", line 1216:
    from libtbx.util import Sorry
usr+sys time: 0.21 seconds
```
Suggest the import should be `from libtbx.utils import Sorry`

**Comment by dagewa** [comment]
It's good to see GPU acceleration being used here. As a simtbx user I am interested in these developments. What do I need to do to get a CUDA enabled build (just for testing with a Quadro K1100M GPU)?

**Comment by dermen** [comment]
This should work, though could change a bit for the better

```
# find your favorite conda install
source ~/miniconda3/etc/profile.d/conda.sh
conda create --name cctbx_cuda
conda activate cctbx_cuda
conda install --file cctbx_py27_linux-64.txt 
conda deactivate # dont need to be active any longer.. 
```

Note the manifest file was found in ```libtbx/auto_build/conda_envs/``` .  (I think we can expect the necessity to do this manually to change soon)

Make empty folder for bootstrap, run hot update if not already done

```
mkdir ~/crys
cd ~/crys
# wget the  latest bootstrap.py
chmod +x boostrap.py
./bootstrap.py  --builder=dials hot update
```

then  path your nvcc (cuda versions 6 -10.1 currently supported)

make the following script called ```~/cuda_startup.sh``` and change accordingly
```
#!/bin/bash
export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda/lib64
```

then set cuda paths and build with the path to your freshly created conda env above

```
source ~/cuda_startup.sh
./bootstrap.py build --use_conda ~/miniconda3/envs/cctbx_cuda --config-flags="--enable_cuda" --nproc 8 --builder=dials  --build-dir cudabuild
```

This should do it, there will hopefully be cuda tests in nanoBragg, but for now just replace ```add_nanoBragg_spots``` with ```add_nanoBragg_spots_cuda``` in any relevant script to check for failures..

**Comment by dermen** [comment]
I've acquired confirmation to merge from Nick, James, and Giles.

**Comment by dagewa** [comment]
@dermen thanks for the instructions, I'll try this out next week.

**Pull request merged**
