### PR TITLE
Building with conda package

### PR DESCRIPTION
**Pull request by bkpoon**
An installed `libtbx.env_config.environment` is introduced that is not normally modifiable. This enables tracking of installed modules as well as newly configured modules. Recompilation of installed modules is disabled.

Running checks to ensure existing SCons behavior is not altered. Testing with conda packages in `cctbx-dev` to iron out build issues before merging.

### CODE REVIEW

**Comment by Anthchirp** [comment]
Don't quite understand what is going on here. Will this require any changes in dxtbx/dials/xia2/etc. packages?

**Comment by bkpoon** [comment]
> Will this require any changes in dxtbx/dials/xia2/etc. packages?

It depends if dxtbx/dials/xia2/etc. are expected to be the last modules to be built by the `cctbx` build system. For example, when building `phenix`, the `dials` module is currently built as well. To get around `dials` from being recompiled, a check (`if not libtbx.env.module_is_installed('dials'):`) could be added before the compilation steps. Alternatively, I was going to remove `dials` from being a configured module and added as a `conda` package dependency for the `phenix` builder (along with `dxtbx`, `xia2`, etc.).

The basic idea is to check for installed modules, then only build the modules that are not installed. There is a new local `libtbx.env_config.enviroment` that tracks the new modules. 

For `dxtbx` I did make a `libpath` branch that prevents the `libpath` from being overwritten. Some additional paths are added to the base SCons build environment to handle include/library paths from the local build directory.

Lastly, `setuptools 50.0` seems to be causing configuration problems when first run. Running `libtbx.refresh` after the crash seems to resolve the problem. The error looks like,
```
2020-08-31T02:33:43.4859040Z Processing: "/Users/runner/work/1/modules/cctbx_project/scitbx/libtbx_refresh.py"
2020-08-31T02:33:43.4859400Z   Generating C++ header files in:
2020-08-31T02:33:43.4859770Z     "/Users/runner/work/1/build/include/scitbx/array_family"
2020-08-31T02:33:43.4860060Z   Generating C++ files in:
2020-08-31T02:33:43.4860420Z     "/Users/runner/work/1/build/include/scitbx/array_family/boost_python"
2020-08-31T02:33:43.4860750Z   Using fable to convert scitbx/lbfgs.f
2020-08-31T02:33:43.4861050Z Updating entry points for scitbx
2020-08-31T02:33:43.4861350Z   1 entries for entry point pytest_randomly.random_seeder
2020-08-31T02:33:43.5130930Z /Users/runner/work/1/miniconda/envs/py36/python.app/Contents/lib/python3.6/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
2020-08-31T02:33:43.5131580Z   warnings.warn("Setuptools is replacing distutils.")
2020-08-31T02:33:43.5160190Z Traceback (most recent call last):
2020-08-31T02:33:43.5160580Z   File "../modules/cctbx_project/libtbx/configure.py", line 34, in <module>
2020-08-31T02:33:43.5161040Z     if not run():
2020-08-31T02:33:43.5161350Z   File "../modules/cctbx_project/libtbx/configure.py", line 29, in run
2020-08-31T02:33:43.5161720Z     libtbx.env_config.cold_start(sys.argv)
2020-08-31T02:33:43.5162110Z   File "/Users/runner/work/1/modules/cctbx_project/libtbx/env_config.py", line 2630, in cold_start
2020-08-31T02:33:43.5162490Z     env.refresh()
2020-08-31T02:33:43.5162830Z   File "/Users/runner/work/1/modules/cctbx_project/libtbx/env_config.py", line 1864, in refresh
2020-08-31T02:33:43.5163240Z     module.process_libtbx_refresh_py()
2020-08-31T02:33:43.5163650Z   File "/Users/runner/work/1/modules/cctbx_project/libtbx/env_config.py", line 2181, in process_libtbx_refresh_py
2020-08-31T02:33:43.5164050Z     exec(to_str(fh.read()), global_vars)
2020-08-31T02:33:43.5164370Z   File "<string>", line 28, in <module>
2020-08-31T02:33:43.5164750Z   File "/Users/runner/work/1/modules/cctbx_project/libtbx/pkg_utils.py", line 252, in define_entry_points
2020-08-31T02:33:43.5165130Z     **kwargs
2020-08-31T02:33:43.5166150Z   File "/Users/runner/work/1/miniconda/envs/py36/python.app/Contents/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
2020-08-31T02:33:43.5166690Z     return distutils.core.setup(**attrs)
2020-08-31T02:33:43.5167570Z   File "/Users/runner/work/1/miniconda/envs/py36/python.app/Contents/lib/python3.6/site-packages/setuptools/_distutils/core.py", line 134, in setup
2020-08-31T02:33:43.5168220Z     ok = dist.parse_command_line()
2020-08-31T02:33:43.5169100Z   File "/Users/runner/work/1/miniconda/envs/py36/python.app/Contents/lib/python3.6/site-packages/setuptools/_distutils/dist.py", line 484, in parse_command_line
2020-08-31T02:33:43.5169660Z     args = self._parse_command_opts(parser, args)
2020-08-31T02:33:43.5170530Z   File "/Users/runner/work/1/miniconda/envs/py36/python.app/Contents/lib/python3.6/site-packages/setuptools/dist.py", line 903, in _parse_command_opts
2020-08-31T02:33:43.5171100Z     nargs = _Distribution._parse_command_opts(self, parser, args)
2020-08-31T02:33:43.5172580Z   File "/Users/runner/work/1/miniconda/envs/py36/python.app/Contents/lib/python3.6/site-packages/setuptools/_distutils/dist.py", line 548, in _parse_command_opts
2020-08-31T02:33:43.5173180Z     "command class %s must subclass Command" % cmd_class)
2020-08-31T02:33:43.5174000Z distutils.errors.DistutilsClassError: command class <class 'setuptools.command.egg_info.egg_info'> must subclass Command
2020-08-31T02:33:43.5735620Z Performing actions: build
2020-08-31T02:33:43.5735940Z 
2020-08-31T02:33:43.5736190Z   removing .pyc files in /Users/runner/work/1/modules, walk? True
2020-08-31T02:33:43.5736590Z   removed 1 files
2020-08-31T02:33:43.5736820Z ===== Running in build: run configure.py
2020-08-31T02:33:43.5737130Z Process failed with return code 1
2020-08-31T02:33:43.5877720Z 
2020-08-31T02:33:43.5958240Z ##[error]Bash exited with code '1'.
2020-08-31T02:33:43.5973480Z ##[section]Finishing: Configure and Build
```

**Comment by Anthchirp** [comment]
> Lastly, `setuptools 50.0` seems to be causing configuration problems when first run.

Adding `os.environ["SETUPTOOLS_USE_DISTUTILS"] = "stdlib"` before the `setuptools` import might help.

**Comment by bkpoon** [comment]
Looks like the `setuptools 50.0` conda package is now marked as broken.
https://github.com/conda-forge/admin-requests/pull/120

**Comment by bkpoon** [comment]
@Anthchirp Here are instructions to build `dials` from an active environment with the alpha `cctbx` package installed. You will need a regular `modules` directory with all the sources you would normally have (I used a normal checkout from the `phenix` builder). Some repositories will need the branches listed below.

1) `annlib_adaptbx` -> `conda`
2) `ccp4io_adaptbx` -> `conda`
3) `cctbx_project` -> `conda_compiler`
4) `dxtbx` -> `libpath`

You will also want an empty `build` directory at the same level as `modules` to replicate the standard structure from `bootstrap.py`.

```
cd build

# dependencies
conda create -y -n test -c cctbx-dev -c conda-forge cctbx
conda activate test
conda install -y --file ../modules/dials/.conda-envs/linux.txt

# configure
libtbx.configure --use_conda dials

# build
make
```

The build is not "installed" so you will need to source a `setpaths` script to set the `$PATH`. Testing for `dxtbx` seems to pass (did not try `--regression`) and 17 failures for `dials` (also without `--regression`). This is on a CentOS 6 machine. I think some are resource errors where too many threads are being created by `numpy`.

I will do some final tests tomorrow on macOS and Windows. Then I will merge the branches for the August release. Bug fixes and some streamlining will go in the September release. Let me know how to reproduce any crashes. Thanks!

**Comment by Anthchirp** [comment]
Sounds good. I don't think anyone from the dials side has capacity to look at this before the cctbx release has landed though. It's more likely that we'll evaluate this for a future release cycle. So please don't wait on us for this.

**Pull request merged**
