### PR TITLE
Update mmcif key names in as_cif_block method of iotbx.merging_statistics.dataset_statistics

### PR DESCRIPTION
**Pull request by jbeilstenedmands**
This PR updates the key names for the `as_cif_block` method of the `iotbx.merging_statistics.dataset_statistics` class, to match the definitions of the pdbx mmcif v5 dictionary for the `reflns` and `reflns_shell` categories (https://mmcif.wwpdb.org/pdbx-mmcif-home-page.html).

The output now validates against v5 of the dictionary, according to the instructions in https://sw-tools.rcsb.org/apps/MMCIF-DICT-SUITE/README-source.

As an example, this was tested within a DIALS installation: 
`xia2 image=$(dials.data get -q x4wide)/X4_wide_M1S4_2_0001.cbf:1:20`

With the `master` branch, validating the output `xia2.mmcif` against the `mmcif_pdbx_v5_next.sdb` dictionary file gives the following errors, which are no longer present when running with this `mmcif_updates` branch:
```
ERROR - In block "AUTOMATIC_DEFAULT_NATIVE", in category "reflns", item "number_unique_obs" is not defined in the reference file
ERROR - In block "AUTOMATIC_DEFAULT_NATIVE", in category "reflns", item "pdbx_Rpim_I_obs" is not defined in the reference file
ERROR - In block "AUTOMATIC_DEFAULT_NATIVE", in category "reflns", item "pdbx_Rrim_I_obs" is not defined in the reference file
ERROR - In block "AUTOMATIC_DEFAULT_NATIVE", in category "reflns", item "Rmerge_I_obs" is not defined in the reference file
ERROR - In block "AUTOMATIC_DEFAULT_NATIVE", in category "reflns", item "meanI_over_sigI_obs" is not defined in the reference file
ERROR - In block "AUTOMATIC_DEFAULT_NATIVE", in category "reflns", item "number_measured_obs" is not defined in the reference file
ERROR - In block "AUTOMATIC_DEFAULT_NATIVE", in category "reflns_shell", item "pdbx_Rpim_I_obs" is not defined in the reference file
ERROR - In block "AUTOMATIC_DEFAULT_NATIVE", in category "reflns_shell", item "pdbx_Rrim_I_obs" is not defined in the reference file
ERROR - In block "AUTOMATIC_DEFAULT_NATIVE", in category "reflns_shell", item "pdbx_netI_over_sigmaI" is not defined in the reference file
```

**Summary of name changes, reflns category**
number_unique_obs -> number_obs
pdbx_Rpim_I_obs -> pdbx_Rpim_I_all
pdbx_Rrim_I_obs -> pdbx_Rrim_I_all
Rmerge_I_obs -> pdbx_Rmerge_I_obs
meanI_over_sigI_obs -> pdbx_netI_over_sigmaI
number_measured_obs -> number_measured_all

**Summary of name changes, reflns_shell category**
pdbx_Rpim_I_obs -> pdbx_Rpim_I_all
pdbx_Rrim_I_obs -> pdbx_Rrim_I_all
pdbx_netI_over_sigmaI -> pdbx_netI_over_sigmaI_obs

### CODE REVIEW

**Comment by olegsobolev** [comment]
Thanks for looking into this. Two issues here.
1. meanI_over_sigI_obs -> pdbx_netI_over_sigmaI (reflns)
[pdbx_netI_over_av_sigmaI](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_reflns.pdbx_netI_over_av_sigmaI.html) should be used instead.

2. pdbx_netI_over_sigmaI -> pdbx_netI_over_sigmaI_obs (reflns_shell)
[meanI_over_sigI_obs](https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_reflns_shell.meanI_over_sigI_obs.html) should be used instead.

In both cases the difference is ```<I>/<sigI>``` which I believe we have and ```<I/sigI>``` which you are suggesting.

Once this is fixed, it should be good to go.

**Comment by olegsobolev** [comment]
I should stand corrected, didn't notice the change in the variable as well. "i_mean_over_sigi_mean" from cctbx is disappeared from the output. It probably should go to pdbx_netI_over_av_sigmaI and meanI_over_sigI_obs or do you have any reason to not output it?

**Comment by jbeilstenedmands** [comment]
Thanks @olegsobolev for taking the time to review this. You are correct that i_mean_over_sigi_mean should also have been included, I have added this back in and checked that the output still validates without issues. If there are no further objections I will merge this in a couple of days.

**Comment by olegsobolev** [comment]
Looks good to me, please feel free to merge at your convenience.

**Pull request merged**
