### PR TITLE
Replace CUDAREAL arrays with vec3 in simtbx/kokkos

### PR DESCRIPTION
**Pull request by Trzs**

### CODE REVIEW

**Comment by nksauter** [comment]
Please hold off until I have a chance to review

**Comment by nksauter** [comment]
Let's keep in mind to make the LS49 unit tests work. 
srun -n 1 libtbx.python "/pscratch/sd/n/nksauter/adse13_249/alcc-recipes/cctbx/modules/LS49/adse13_187/cyto_batch.py" N_total=1 test_pixel_congruency=True mosaic_method=double_random mosaic_spread_samples=50 write_output=False test_without_mpi=True log.outdir=mp1k nxmx_local_data=/global/cfs/cdirs/m3562/der/master_files/run_000795.JF07T32V01_master.h5 context=kokkos_gpu

gives this error:
terminate called after throwing an instance of 'std::runtime_error'
  what():  Kokkos allocation "device_Fhkl" is being deallocated after Kokkos::finalize was called

Traceback functionality not available

But this message is just produced by the traceback process and hides a more serious underlying problem:
Traceback (most recent call last):
  File "/pscratch/sd/n/nksauter/adse13_249/alcc-recipes/cctbx/modules/LS49/adse13_187/cyto_batch.py", line 552, in <module>
    run_batch_job()
  File "/pscratch/sd/n/nksauter/adse13_249/alcc-recipes/cctbx/modules/LS49/adse13_187/cyto_batch.py", line 537, in run_batch_job
    rank=rank,params=params
  File "/pscratch/sd/n/nksauter/adse13_249/alcc-recipes/cctbx/modules/LS49/adse13_187/cyto_batch.py", line 409, in tst_one
    assert np.allclose(pdata, JF16M_numpy_array), "max per-pixel difference: %f photons"%abs_diff
AssertionError: max per-pixel difference: nan photons

**Comment by nksauter** [comment]
Felix,
I've added you to the project m3562.  Can you read the file now?
Ultimately these tests need to be refactored to not need local files on
$CFS.  It is on the radar screen for Aaron & I.

Nick

**Comment by Trzs** [comment]
Nick,

Yes, now I can read the file, thank you. I can also reproduce the error.

Felix

**Comment by nksauter** [comment]
OK, I'm glad we both get the same result.
Nick

**Comment by Trzs** [comment]
Nick,

please check the latest version. For me this solved the problems.

Felix.

**Pull request closed without merging**
