### PR TITLE
Write the libtbx eggs to the build directory

### PR DESCRIPTION
**Pull request by hattne**
Tell setuptools to put the libtbx eggs in the build directory and eliminate the chdir around the setup() invocation.  This allows libtbx.refresh to run on a custom Python where write-access to site-packages directory is restricted.

### CODE REVIEW

**Comment by Anthchirp** [comment]
Tested this in a clean conda environment using the pull request #383 as a test case(*):
```bash
$ python bootstrap.py hot update base build --git-ssh --nproc=4 --use-conda 
$ . build/setpaths.sh 
$ cd modules/cctbx_project/
$ git checkout -b hattne-master master
$ git pull git://github.com/hattne/cctbx_project.git master
$ git merge origin/random
$ mkdir ../../wrong
$ cd ../../wrong
$ libtbx.configure ../modules/cctbx_project
$ cd ..
$ libtbx.python -c "import pkg_resources;print(list(pkg_resources.iter_entry_points('pytest_randomly.random_seeder')))"
```
and in a clean standard base build environment:
```bash
$ python bootstrap.py hot update base build --git-ssh --nproc=4
$ . build/setpaths.sh
$ cd modules/cctbx_project/
$ git checkout -b hattne-master master
$ git pull git://github.com/hattne/cctbx_project.git master
$ git merge origin/random
$ mkdir ../../wrong
$ cd ../../wrong
$ libtbx.configure ../modules/cctbx_project
$ cd ..
$ libtbx.python -c "import pkg_resources;print(list(pkg_resources.iter_entry_points('pytest_randomly.random_seeder')))"
```

While both versions print the expected output, the egg-info directories end up in `/wrong`, with the eg. `lib/libtbx.scitbx.egg-link` files pointing to that location.
This is not the case with the current code in `master`, where the `/wrong` directory is kept clean.

So it looks to me like this patch does not achieve the stated aims?


(*) I later noticed that this extra step was not necessary for verification, as `dxtbx` is configured by default and that already declares entry points. However it did allow me to confirm that PR #383 works as intended.

**Comment by hattne** [comment]
OK, the previous iteration would only work if one refreshed in the build directory; looks like --script-dir does not change the destination of the egg.

Current iteration was tested in a conda environment and "standard base build"; .egg-info goes into build directory and .egg-link points to the right place.

**Comment by Anthchirp** [comment]
Alas this doesn't work either.
Running the conda variant fails at the start of the `bootstrap.py build` step with:
```Updating entry points for dxtbx
  117 entries for entry point dxtbx.format
TEST FAILED: /scratch2/wra62962/files/temp/c387/conda/build/lib does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /scratch2/wra62962/files/temp/c387/conda/build/lib

and your PYTHONPATH environment variable currently contains:

    ''

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations


Please make the appropriate changes for your system and try again.
Process failed with return code 1
```

**Comment by Anthchirp** [comment]
Instructions I used, starting from just an empty directory:
```
wget https://raw.githubusercontent.com/cctbx/cctbx_project/master/libtbx/auto_build/bootstrap.py
python bootstrap.py hot update  --git-ssh --use-conda --nproc=4
cd modules/cctbx_project
git checkout -b hattne-master master
git pull git://github.com/hattne/cctbx_project.git master
cd ../..
python bootstrap.py base build  --git-ssh --use-conda --nproc=4
```

**Comment by Anthchirp** [comment]
also fails with a normal base build without conda with the same error (just takes longer to get to that point)

**Comment by hattne** [comment]
OK, now I'm confused.  I assume this is setuptools failing a sanity check–if build/lib won't eventually be in path, I've got a lot of understanding to do still.

**Comment by hattne** [comment]
Next idea: how about using egg_info to write an egg to the build directory directly, and omit the egg-link entirely?

**Comment by Anthchirp** [comment]
@hattne any comments on the change? Otherwise I will just merge in a few days.

**Pull request merged**
